#config_version=6

mode:
  start_events: ball_started
  stop_events:
    - skill_failed
    - skillshot_hit
  priority: 500


sequence_shots:
  inner_loop_skill_sequence:
    switch_sequence: s_right_orbit, s_inner_orbit
    sequence_timeout: 4.5s


shots:
  skillshot_side_targets:
    switch: s_tshirt_bottom_standup, s_tshirt_top_standup
    profile: skill_shot_profile
    advance_events: advance_skill_side_targets
    show_tokens:
      led: l_tshirttopcircle_led, l_tshirtbottomcircle_led
  skillshot_hideout_plunge:
    switch: s_scoop
    profile: skill_shot_profile
    advance_events: advance_skill_hideout
    show_tokens:
      led: l_innerloop_arrow_led, l_innerloopcombo_circle_led, l_scoop_arrow_led
  skillshot_super:
    hit_events: inner_loop_skill_sequence_hit
    profile: skill_shot_profile
    advance_events: advance_skill_super
    show_tokens:
      led: l_innerloop_arrow_led, l_innerloopcombo_circle_led, l_rightorbitcombo_circle_led
  skillshot_left_outlane:
    switch: s_left_outlane
    profile: skill_shot_profile
    advance_events: advance_skill_left_outlane
    show_tokens:
      led: l_leftoutlane_circle_led
  skillshot_drop_targets:
    switch: s_three_bank_bottom, s_three_bank_middle, s_three_bank_top
    profile: skill_shot_profile
    advance_events: advance_skill_drop_targets
    show_tokens:
      led: l_lowerdrop_circle_led, l_middledrop_circle_led, l_upperdrop_circle_led


shot_profiles:
  skill_shot_profile:
    advance_on_hit: true
    states:
      - name: off
        show: off
      - name: lit
        show: flash_color
        show_tokens:
          color: 999999
        speed: 4
    loop: true


shot_groups:
  skillshot:
    shots: skillshot_side_targets, skillshot_hideout_plunge, skillshot_super, skillshot_left_outlane, skillshot_drop_targets
    disable_rotation_events: ball_out, skillshot_off_hit
    reset_events: skillshot_lit_hit
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    restart_events: mode_skill_shot_started


variable_player:
  skillshot_lit_hit:
    score: 1000000
    bonus_multiplier:
      int: 2
      action: add


timers:
  skill_shot_timeout:
    start_value: 0
    end_value: 4
    direction: up
    tick_interval: 1
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success
      - action: reset
        event: ball_starting
      - action: pause
        event: ball_starting


slide_player:
  mode_skill_shot_started:
    skillshot_overlay:
      action: play
      priority: 950000
  skillshot_hit:
    skillshot_overlay:
      action: remove
  skill_failed:
    skillshot_overlay:
      action: remove


random_event_player:
  mode_skill_shot_started:
    events:
    - advance_skill_side_targets
    - advance_skill_drop_targets
    - advance_skill_super
    - advance_skill_hideout
    - advance_skill_left_outlane

event_player:
  timer_skill_shot_timeout_complete: skill_failed
