#config_version=6
mode:
  start_events: ball_started
  stop_events:
    - skill_success
    - skill_failed
  priority: 500

shots:
  skill_side_target_1:
    switch: s_tshirt_bottom_standup
    profile: skill_shot_profile
    advance_events: mode_skillshot_started
  skill_side_target_2:
    switch: s_tshirt_top_standup
    profile: skill_shot_profile
    advance_events: mode_skillshot_started

shot_groups:
  skill_shot:
    shots: skill_side_target_1, skill_side_target_2

shot_profiles:
  skill_shot_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash_color
        show_tokens:
          color: red
        speed: 4
      - name: lit
        show: on
    loop: true

variable_player:
  skill_success:
    score: 1000000

timers:
  skill_shot_timeout:
    start_value: 0
    end_value: 5     # set the timeout of your skill shot here
    direction: up
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success  # replace "plunger_lane" with the name of your plunger device

state_machines:
  skill_shot_success:
    debug: true
    states:
      start:
        label: Skill shot ready
      success:
        label: Skill successful
        events_when_started: skill_success
      failed:
        label: Skill failed
        events_when_started: skill_failed
    transitions:
      - source: start
        target: success
        events: skill_shot_flashing_hit
      - source: start
        target: failed
        events: skill_shot_unlit_hit, timer_skill_shot_timeout_complete

slide_player:
  mode_skillshot_started:
    skillshot_overlay:
      action: play
      priority: 800000
  skillshot_hit:
    skillshot_overlay:
      action: remove
    skillshot_success_overlay:
      action: play
      duration: 3s
      priority: 800000
  skillshot_failed:
    skillshot_overlay:
      action: remove