#config_version=6

mode:
  start_events: start_superpops
  stop_events: mode_superpops_complete
  priority: 20000


variable_player:
  pop1_hit:
    score: 100000 * current_player.playfield_x
  pop2_hit:
    score: 100000 * current_player.playfield_x
  pop3_hit:
    score: 100000 * current_player.playfield_x


timers:
  superpops_timer:
    start_value: 0
    end_value: 30
    tick_interval: 1s
    start_running: True
    control_events:
      - event: mode_superpops_started
        action: restart
      - event: ball_ending
        action: stop

event_player:
  timer_superpops_timer_complete: mode_superpops_complete


random_event_player:
  mode_superpops_started:
    events:
      - mixmastermike1_sound
      - mixmastermike2_sound
      - mixmastermike3_sound
      - mixmastermike4_sound
      - mixmastermike5_sound
      - mixmastermike6_sound


sound_player:
  mixmastermike1_sound:
    name_mixmastermike_1:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice
  mixmastermike2_sound:
    name_mixmastermike_2:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice
  mixmastermike3_sound:
    name_mixmastermike_3:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice
  mixmastermike4_sound:
    name_mixmastermike_4:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice
  mixmastermike5_sound:
    name_mixmastermike_5:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice
  mixmastermike6_sound:
    name_mixmastermike_6:
      action: load
      bus: voice
    superpops_callout:
      action: load
      bus: voice

