#config_version=6

mode:
  start_events: carousel_item_selected{item=="fingerlickingood"}
  stop_events: mode_fingerlickingood_stop, mode_fingerlickingood_failed, mode_fingerlickingood_success, ball_will_end
  priority: 1001



shots:
  fingerlickingood_pop_standup_hit:
    hit_events: pop_standup_hit


variable_player:
  mode_fingerlickingood_started:
    mode_blocking_flag:
      int: 1
      action: set
    fingerlickingood_boost:
      int: 1
      action: set
  timer_fingerlickingood_intro_show_tick:
    fingerlickingood_intro_show_variable_times_100:
      int: device.timers.fingerlickingood_intro_show.ticks * 100
      action: set
  timer_fingerlickingood_time_remaining_tick:
    fingerlickingood_time_remaining_variable_times_1:
      int: device.timers.fingerlickingood_time_remaining.ticks * 1
      action: set
  fingerlickingood_pop_standup_hit:
    score: 3000000 * current_player.fingerlickingood_boost * current_player.playfield_x * current_player.loop_shot_multiplier
    mode_fingerlickingood_score: 3000000 * current_player.fingerlickingood_boost * current_player.playfield_x * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  right_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 110 * current_player.playfield_x
  left_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 110 * current_player.playfield_x
  right_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 1110 * current_player.playfield_x
  left_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 1110 * current_player.playfield_x
  s_left_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 10 * current_player.playfield_x
  s_right_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 10 * current_player.playfield_x
  pop1_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 1110 * current_player.playfield_x
  pop2_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 1110 * current_player.playfield_x
  pop3_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 1110 * current_player.playfield_x
  upper_pop_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 5010 * current_player.playfield_x
  captive_ball_hit:
    score: 
      int: 10010 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 10010 * current_player.playfield_x
  spinner_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_fingerlickingood_score: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
  bottom_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 2220 * current_player.playfield_x
  middle_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 2220 * current_player.playfield_x
  top_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 2220 * current_player.playfield_x
  scoop_hit:
    score: 
      int: 2310 * current_player.playfield_x * current_player.scoop_multiplier
      block: True
    mode_fingerlickingood_score: 2310 * current_player.playfield_x * current_player.scoop_multiplier
  tshirt_top_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 5010 * current_player.playfield_x
  tshirt_bottom_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 5010 * current_player.playfield_x
  three_bank_standup_hit:
    score: 
      int: 20010 * current_player.playfield_x
      block: True
    mode_fingerlickingood_score: 20010 * current_player.playfield_x
  s_left_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_fingerlickingood_score: 110 * current_player.playfield_x * current_player.left_orbit_multiplier
  s_right_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.right_orbit_multiplier
      block: True
    mode_fingerlickingood_score: 110 * current_player.playfield_x * current_player.right_orbit_multiplier
  s_inner_orbit_active:
    score: 
      int: 1010 * current_player.playfield_x * current_player.upper_loop_multiplier
      block: True
    mode_fingerlickingood_score: 1010 * current_player.playfield_x * current_player.upper_loop_multiplier
  left_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.left_ramp_multiplier
      block: True
    mode_fingerlickingood_score: 3010 * current_player.playfield_x * current_player.left_ramp_multiplier
    fingerlickingood_boost:
      int: 1
      action: add
  right_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.right_ramp_multiplier
      block: True
    mode_fingerlickingood_score: 3010 * current_player.playfield_x * current_player.right_ramp_multiplier
    fingerlickingood_boost:
      int: 1
      action: add
  left_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_fingerlickingood_score: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
  right_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.right_orbit_multiplier
      block: True
    mode_fingerlickingood_score: 1010 * current_player.playfield_x * current_player.right_orbit_multiplier
  inner_loop_hit:
    score: 
      int: 2010 * current_player.playfield_x * current_player.upper_loop_multiplier
      block: True
    mode_fingerlickingood_score: 2010 * current_player.playfield_x * current_player.upper_loop_multiplier


slide_player:
  mode_fingerlickingood_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    fingerlickingood:
      action: play
      priority: 500000
    fingerlickingood_instructions:
      action: play
      priority: 500001
      expire: 6s
  timer_fingerlickingood_intro_show_complete:
    fingerlickingood_boost:
      action: play
      priority: 800000
    fingerlickingood_instructions:
      action: remove
    fingerlickingood_display_timer:
      action: play
      priority: 1000000


sound_player:
  mode_fingerlickingood_started:
    fingerlickingoodmusic:
      action: play
      bus: music
  finger_boost:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  fingerlickingood_pop_standup_hit:
    success_finish:
      action: play
      bus: effects
      max_queue_time: 1s
  tencallout1:
    ten_callout1:
      action: play
      bus: voice
      max_queue_time: 1s
  tencallout2:
    ten_callout2:
      action: play
      bus: voice
      max_queue_time: 1s
  tencallout3:
    ten_callout3:
      action: play
      bus: voice
      max_queue_time: 1s


random_event_player:
  timer_fingerlickingood_time_remaining_tick{current_player.fingerlickingood_time_remaining_variable_times_1==10}:
    events:
      - tencallout1
      - tencallout2
      - tencallout3


ball_holds:
  fingerlickingood_scoop_hold:
    balls_to_hold: 1
    hold_devices: bd_scoop
    enable_events: mode_fingerlickingood_started
    disable_events: timer_fingerlickingood_intro_show_complete
    release_one_events: timer_fingerlickingood_intro_show_complete


timers:
  fingerlickingood_intro_show:
    start_value: 0
    end_value: 6
    control_events:
      - action: start
        event: mode_fingerlickingood_started
      - action: jump
        value: 6
        event: flipper_cancel{device.ball_holds.fingerlickingood_scoop_hold.balls_held==1}
  fingerlickingood_time_remaining:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_fingerlickingood_intro_show_complete
      - action: pause
        event: fingerlickingood_pop_standup_hit
      - action: reset
        event: mode_fingerlickingood_started
      - action: add
        value: 7
        event: add_fingerlickingood_time_7s


event_player:
  timer_fingerlickingood_time_remaining_complete: mode_fingerlickingood_failed
  fingerlickingood_pop_standup_hit: mode_fingerlickingood_success
  left_ramp_hit: finger_boost, add_fingerlickingood_time_7s
  right_ramp_hit: finger_boost, add_fingerlickingood_time_7s


shot_profiles:
  fingerlickingood_shot:
    advance_on_hit: False
    states:
      - name: "off"
    loop: False


show_player:
  mode_fingerlickingood_started:
    fingerlickingood_backboard_show:
      action: play
      loops: -1
    fingerlickingood_stadium_intro_lights:
      action: play
      loops: -1
    fingerlickingood_pops_show:
      action: play
      loops: -1
  timer_fingerlickingood_intro_show_complete:
    fingerlickingood_stadium_intro_lights:
      action: stop



blinkenlight_player:
  mode_fingerlickingood_started:
    bl_leftramp_arrow_led:
      color: FF46A2
    bl_rightramp_arrow_led:
      color: FF46A2
    bl_lowerrightstandup_circle_led:
      color: FA8072

