#config_version=6

mode:
  start_events: start_superstandups
  stop_events: mode_superstandups_complete
  priority: 20000

variable_player:
  pop_standup_hit:
    score: 100000 * current_player.playfield_x
  upper_pop_standup_hit:
    score: 100000 * current_player.playfield_x
  three_bank_standup_hit:
    score: 100000 * current_player.playfield_x
  tshirt_top_standup_hit:
    score: 100000 * current_player.playfield_x
  tshirt_bottom_standup_hit:
    score: 100000 * current_player.playfield_x


timers:
  superstandups_timer:
    start_value: 0
    end_value: 30
    tick_interval: 1s
    start_running: True
    control_events:
      - event: mode_superstandups_started
        action: restart
      - event: ball_ending
        action: stop

event_player:
  timer_superstandups_timer_complete: mode_superstandups_complete


random_event_player:
  mode_superstandups_started:
    events:
      - mca1_sound
      - mca2_sound
      - mca3_sound
      - mca4_sound
      - mca5_sound
      - mca6_sound
      - mca7_sound
      - mca8_sound
      - mcarobot_sound


sound_player:
  mca1_sound:
    name_mca_1:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca2_sound:
    name_mca_2:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca3_sound:
    name_mca_3:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca4_sound:
    name_mca_4:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca5_sound:
    name_mca_5:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca6_sound:
    name_mca_6:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca7_sound:
    name_mca_7:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mca8_sound:
    name_mca_8:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice
  mcarobot_sound:
    name_mca_robot:
      action: load
      bus: voice
    superstandups_callout:
      action: load
      bus: voice

