#config_version=6

mode_settings:
  selectable_items:
    - gameover{machine.game_just_played==1}
    - last_scores_4p{machine.game_just_played==1}
    - mpf_logo
    - fast_logo
    - riot_logo
    - specialthanks
    - credits
    - pressstart
    - version
    - beastie_pinball_logo
    - show_logo
    - makercredits
    - dedicated
    - highscoregrandchampion
    - highscore1
    - highscore2
    - highscore3
    - highscore4
    - highscoremultiballs
    - highscoremodes1
    - highscoremodes2
    - highscoremodes3
    - highscoremodes4
    - highscoremodes5
    - highscoremodes6
    - highscoremodes7
  next_item_events: s_right_flipper_active, timer_attract_carousel_timer_complete
  previous_item_events: s_left_flipper_active

sequences:
  mca_sequence:
    events:
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_left_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_left_flipper_active
    - s_right_flipper_active
    - s_left_flipper_active
    disable_events: game_starting
    reset_on_complete: True
    restart_events: mode_attract_started, adr_sequence_hit, mca_sequence_hit, flipper_cancel, christmas_sequence_hit, muppets_sequence_hit
    events_when_complete: mca_sequence_hit
  adr_sequence:
    events:
    - s_right_flipper_active
    - s_left_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_left_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_right_flipper_active
    - s_left_flipper_active
    disable_events: game_starting
    reset_on_complete: True
    restart_events: mode_attract_started, adr_sequence_hit, mca_sequence_hit, flipper_cancel, christmas_sequence_hit, muppets_sequence_hit
    events_when_complete: adr_sequence_hit
  christmas_sequence:
    events:
      - s_right_flipper_active
      - s_left_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
    disable_events: game_starting
    reset_on_complete: True
    restart_events: mode_attract_started, adr_sequence_hit, mca_sequence_hit, flipper_cancel, christmas_sequence_hit, muppets_sequence_hit
    events_when_complete: christmas_sequence_hit
  muppets_sequence:
    events:
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_right_flipper_active
      - s_left_flipper_active
    disable_events: game_starting
    reset_on_complete: True
    restart_events: mode_attract_started, adr_sequence_hit, mca_sequence_hit, flipper_cancel, christmas_sequence_hit, muppets_sequence_hit
    events_when_complete: muppets_sequence_hit


slide_player:
  mode_attract_started{machine.game_just_played==0}:
    loading:
      action: remove
    attract_load:
      action: play
      priority: 1000000
  timer_attract_intro_timer_complete{machine.game_just_played==0}:
    attract_load:
      action: remove
    attract:
      action: play
      priority: 10000
  mode_attract_started{machine.game_just_played==1}:
    loading:
      action: remove
    match_normal_slide:
      action: remove
    match_mahjong_slide:
      action: remove
    match_mother_slide:
      action: remove
    match_grammy_slide:
      action: remove
    no_match_normal_slide:
      action: remove
    no_match_mahjong_slide:
      action: remove
    no_match_mother_slide:
      action: remove
    no_match_grammy_slide:
      action: remove
    attract:
      action: play
      priority: 1000
  mca_sequence_hit:
    attract_load:
      action: remove
    attract:
      action: remove
    ghostbusters:
      action: play
      priority: 1100000
  timer_mca_attract_video_timer_complete:
    ghostbusters:
      action: remove
    attract:
      action: play
      priority: 1000
  adr_sequence_hit:
    attract_load:
      action: remove
    attract:
      action: remove
    friends:
      action: play
      priority: 1100000
  timer_adr_attract_video_timer_complete:
    friends:
      action: remove
    attract:
      action: play
      priority: 1000
  christmas_sequence_hit:
    attract_load:
      action: remove
    attract:
      action: remove
    jinglebells:
      action: play
      priority: 1100000
  timer_christmas_attract_video_timer_complete:
    jinglebells:
      action: remove
    attract:
      action: play
      priority: 1000
  muppets_sequence_hit:
    attract_load:
      action: remove
    attract:
      action: remove
    beastiemuppets:
      action: play
      priority: 1100000
  timer_muppets_attract_video_timer_complete:
    beastiemuppets:
      action: remove
    attract:
      action: play
      priority: 1000


sound_player:
  mode_attract_started{machine.game_just_played==0}:
    attract_crowd:
      bus: effects
      action: play
  mode_attract_started{machine.game_just_played==1}:
    postgame_instrumental_random:
      action: replace
      bus: music
      fade_out: 5s
  mca_sequence_hit:
    attract_crowd:
      action: stop
      bus: effects
    postgame_instrumental_random:
      action: stop
      bus: music
  timer_mca_attract_video_timer_complete:
    attract_crowd:
      bus: effects
      action: play
  adr_sequence_hit:
    attract_crowd:
      action: stop
      bus: effects
    postgame_instrumental_random:
      action: stop
      bus: music
  timer_adr_attract_video_timer_started:
    friendsmusic:
      action: play
      bus: music
  timer_adr_attract_video_timer_complete:
    attract_crowd:
      bus: effects
      action: play
  christmas_sequence_hit:
    attract_crowd:
      action: stop
      bus: effects
    postgame_instrumental_random:
      action: stop
      bus: music
  timer_christmas_attract_video_timer_complete:
    attract_crowd:
      bus: effects
      action: play
  muppets_sequence_hit:
    attract_crowd:
      action: stop
      bus: effects
    postgame_instrumental_random:
      action: stop
      bus: music
  timer_muppets_attract_video_timer_complete:
    attract_crowd:
      bus: effects
      action: play


timers:
  attract_carousel_timer:
    end_value: 5
    tick_interval: 1s
    start_running: False
    control_events:
      - event: carousel_item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart
      - event: timer_attract_intro_timer_complete
        action: start
      - event: game_ended
        action: start
      - event: mca_sequence_hit
        action: pause
      - event: adr_sequence_hit
        action: pause
      - event: christmas_sequence_hit
        action: pause
      - event: muppets_sequence_hit
        action: pause
      - event: slide_ghostbusters_removed
        action: restart
      - event: slide_friends_removed
        action: restart
      - event: slide_beastiemuppets_removed
        action: restart
      - event: slide_jinglebells_removed
        action: restart
  attract_intro_timer:
    end_value: 16
    tick_interval: 1s
    start_running: True
    control_events:
      - event: mode_attract_started{machine.game_just_played==0}
        action: restart
      - event: game_started
        action: stop
  mca_attract_video_timer:
    end_value: 192
    tick_interval: 1s
    start_running: False
    control_events:
      - event: slide_ghostbusters_active
        action: restart
      - event: game_started
        action: stop
      - event: flipper_cancel
        action: jump
        value: 192
      - event: slide_ghostbusters_removed
        action: jump
        value: 0
      - event: slide_ghostbusters_removed
        action: pause
  adr_attract_video_timer:
    end_value: 49
    tick_interval: 1s
    start_running: False
    control_events:
      - event: slide_friends_active
        action: restart
      - event: game_started
        action: stop
      - event: flipper_cancel
        action: jump
        value: 49
      - event: slide_friends_removed
        action: jump
        value: 0
      - event: slide_friends_removed
        action: pause
  christmas_attract_video_timer:
    end_value: 54
    tick_interval: 1s
    start_running: False
    control_events:
      - event: slide_jinglebells_active
        action: restart
      - event: game_started
        action: stop
      - event: flipper_cancel
        action: jump
        value: 54
      - event: slide_jinglebells_removed
        action: jump
        value: 0
      - event: slide_jinglebells_removed
        action: pause
  muppets_attract_video_timer:
    end_value: 54
    tick_interval: 1s
    start_running: False
    control_events:
      - event: slide_beastiemuppets_active
        action: restart
      - event: game_started
        action: stop
      - event: flipper_cancel
        action: jump
        value: 54
      - event: slide_beastiemuppets_removed
        action: jump
        value: 0
      - event: slide_beastiemuppets_removed
        action: pause


widget_player:
  carousel_item_highlighted{item=="gameover"}:
    attract_gameover:
      action: play
      slide: attract
  carousel_item_highlighted{item!="gameover"}:
    attract_gameover:
      action: remove
  carousel_item_highlighted{item=="last_scores_1p"}:
    attract_last_scores_1p:
      action: play
      slide: attract
  carousel_item_highlighted{item!="last_scores_1p"}:
    attract_last_scores_1p:
      action: remove
  carousel_item_highlighted{item=="last_scores_2p"}:
    attract_last_scores_2p:
      action: play
      slide: attract
  carousel_item_highlighted{item!="last_scores_2p"}:
    attract_last_scores_2p:
      action: remove
  carousel_item_highlighted{item=="last_scores_3p"}:
    attract_last_scores_3p:
      action: play
      slide: attract
  carousel_item_highlighted{item!="last_scores_3p"}:
    attract_last_scores_3p:
      action: remove
  carousel_item_highlighted{item=="last_scores_4p"}:
    attract_last_scores_4p:
      action: play
      slide: attract
  carousel_item_highlighted{item!="last_scores_4p"}:
    attract_last_scores_4p:
      action: remove
  carousel_item_highlighted{item=="mpf_logo"}:
    attract_mpf_logo:
      action: play
      slide: attract
  carousel_item_highlighted{item!="mpf_logo"}:
    attract_mpf_logo:
      action: remove
  carousel_item_highlighted{item=="beastie_pinball_logo"}:
    attract_beastie_pinball_logo:
      action: play
      slide: attract
  carousel_item_highlighted{item!="beastie_pinball_logo"}:
    attract_beastie_pinball_logo:
      action: remove
  carousel_item_highlighted{item=="show_logo"}:
    attract_pinball_show:
      action: play
      slide: attract
  carousel_item_highlighted{item!="show_logo"}:
    attract_pinball_show:
      action: remove
  carousel_item_highlighted{item=="fast_logo"}:
    attract_fast_logo:
      action: play
      slide: attract
  carousel_item_highlighted{item!="fast_logo"}:
    attract_fast_logo:
      action: remove
  carousel_item_highlighted{item=="riot_logo"}:
    attract_riot_logo:
      action: play
      slide: attract
  carousel_item_highlighted{item!="riot_logo"}:
    attract_riot_logo:
      action: remove
  carousel_item_highlighted{item=="specialthanks"}:
    attract_specialthanks:
      action: play
      slide: attract
  carousel_item_highlighted{item!="specialthanks"}:
    attract_specialthanks:
      action: remove
  carousel_item_highlighted{item=="credits"}:
    attract_credits:
      action: play
      slide: attract
  carousel_item_highlighted{item!="credits"}:
    attract_credits:
      action: remove
  carousel_item_highlighted{item=="pressstart"}:
    attract_pressstart:
      action: play
      slide: attract
  carousel_item_highlighted{item!="pressstart"}:
    attract_pressstart:
      action: remove
  carousel_item_highlighted{item=="version"}:
    attract_version:
      action: play
      slide: attract
  carousel_item_highlighted{item!="version"}:
    attract_version:
      action: remove
  carousel_item_highlighted{item=="makercredits"}:
    attract_makercredits:
      action: play
      slide: attract
  carousel_item_highlighted{item!="makercredits"}:
    attract_makercredits:
      action: remove
  carousel_item_highlighted{item=="dedicated"}:
    attract_dedicated:
      action: play
      slide: attract
  carousel_item_highlighted{item!="dedicated"}:
    attract_dedicated:
      action: remove
  carousel_item_highlighted{item=="highscoregrandchampion"}:
    attract_highscoregrandchampion:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoregrandchampion"}:
    attract_highscoregrandchampion:
      action: remove
  carousel_item_highlighted{item=="highscore1"}:
    attract_highscore1:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscore1"}:
    attract_highscore1:
      action: remove
  carousel_item_highlighted{item=="highscore2"}:
    attract_highscore2:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscore2"}:
    attract_highscore2:
      action: remove
  carousel_item_highlighted{item=="highscore3"}:
    attract_highscore3:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscore3"}:
    attract_highscore3:
      action: remove
  carousel_item_highlighted{item=="highscore4"}:
    attract_highscore4:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscore4"}:
    attract_highscore4:
      action: remove
  carousel_item_highlighted{item=="highscoremultiballs"}:
    attract_highscoremultiballs:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremultiballs"}:
    attract_highscoremultiballs:
      action: remove
  carousel_item_highlighted{item=="highscoremodes1"}:
    attract_highscoremodes1:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes1"}:
    attract_highscoremodes1:
      action: remove
  carousel_item_highlighted{item=="highscoremodes2"}:
    attract_highscoremodes2:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes2"}:
    attract_highscoremodes2:
      action: remove
  carousel_item_highlighted{item=="highscoremodes3"}:
    attract_highscoremodes3:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes3"}:
    attract_highscoremodes3:
      action: remove
  carousel_item_highlighted{item=="highscoremodes4"}:
    attract_highscoremodes4:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes4"}:
    attract_highscoremodes4:
      action: remove
  carousel_item_highlighted{item=="highscoremodes5"}:
    attract_highscoremodes5:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes5"}:
    attract_highscoremodes5:
      action: remove
  carousel_item_highlighted{item=="highscoremodes6"}:
    attract_highscoremodes6:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes6"}:
    attract_highscoremodes6:
      action: remove
  carousel_item_highlighted{item=="highscoremodes7"}:
    attract_highscoremodes7:
      action: play
      slide: attract
  carousel_item_highlighted{item!="highscoremodes7"}:
    attract_highscoremodes7:
      action: remove



show_player:
  mode_attract_started:
    attract_light_show_new:
      action: play
      priority: 1000
      loops: -1
#    attract_stadium_light_show:
#      action: play
#      priority: 1000
#      loops: -1
    bonus_count_show_blue:
      action: stop
    bonus_count_show_green:
      action: stop
    bonus_count_show_orange:
      action: stop
    bonus_count_show_pink:
      action: stop
    bonus_count_show_purple:
      action: stop
    bonus_count_show_red:
      action: stop
    bonus_count_show_yellow:
      action: stop
  mode_attract_stopping:
    attract_light_show_new:
      action: stop
#    attract_stadium_light_show:
#      action: stop
    christmas_lights:
      action: stop
    friends_lights:
      action: stop
    ghostbusters_lights:
      action: stop
    muppets_lights:
      action: stop
  mca_sequence_hit:
    attract_light_show_new:
      action: stop
#    attract_stadium_light_show:
#      action: stop
    ghostbusters_lights:
      action: play
      priority: 1000
      loops: -1
  timer_mca_attract_video_timer_complete:
    ghostbusters_lights:
      action: stop
    attract_light_show_new:
      action: play
      priority: 1000
      loops: -1
#    attract_stadium_light_show:
#      action: play
#      priority: 1000
#      loops: -1
  adr_sequence_hit:
    attract_light_show_new:
      action: stop
#    attract_stadium_light_show:
#      action: stop
    friends_lights:
      action: play
      priority: 1000
      loops: -1
  timer_adr_attract_video_timer_complete:
    friends_lights:
      action: stop
    attract_light_show_new:
      action: play
      priority: 1000
      loops: -1
#    attract_stadium_light_show:
#      action: play
#      priority: 1000
#      loops: -1
  christmas_sequence_hit:
    attract_light_show_new:
      action: stop
#    attract_stadium_light_show:
#      action: stop
    christmas_lights:
      action: play
      priority: 1000
      loops: -1
  timer_christmas_attract_video_timer_complete:
    christmas_lights:
      action: stop
    attract_light_show_new:
      action: play
      priority: 1000
      loops: -1
#    attract_stadium_light_show:
#      action: play
#      priority: 1000
#      loops: -1
  muppets_sequence_hit:
    attract_light_show_new:
      action: stop
#    attract_stadium_light_show:
#      action: stop
    muppets_lights:
      action: play
      priority: 1000
      loops: -1
  timer_muppets_attract_video_timer_complete:
    muppets_lights:
      action: stop
    attract_light_show_new:
      action: play
      priority: 1000
      loops: -1
#    attract_stadium_light_show:
#      action: play
#      priority: 1000
#      loops: -1

