#config_version=6

slide_player:
  mode_attract_started:
    loading:
      action: remove
    attract:
      action: play
      priority: 1000

sound_player:
  mode_attract_started:
    attract_crowd:
      bus: effects
