#config_version=6

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100


counters:
  battery_charged_status:
    count_events: spinner_hit{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and current_player.mode_blocking_flag==0 and current_player.girls_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}
    events_when_complete: battery_charged
    starting_count: 20
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: True
    disable_on_complete: True
    reset_on_complete: False
    disable_events: multiball_chcheckitout_started, mode_makesomenoise_started, multiball_bodymovin_started, mode_girls_started, ball_is_ending
    enable_events: ball_started, multiball_chcheckitout_ended, multiball_bodymovin_ended, multiball_makesomenoise_ended, mode_girls_stopped
    restart_events: mode_intergalactic_stopped, mode_intergalactic_success, mode_paulrevere_stopped, mode_paulrevere_success, mode_tripletrouble_stopped, mode_tripletrouble_success, mode_sabotage_stopped, mode_sabotage_success, mode_fingerlickingood_stopped, mode_fingerlickingood_success, mode_toomanyrappers_stopped, mode_toomanyrappers_success, mode_threemcsand1dj_stopped, mode_threemcsand1dj_success, mode_highplainsdrifter_stopped, mode_highplainsdrifter_success
    control_events:
      - event: mode_batterycharger_started{current_player.ball==1}
        action: jump
        value: 0
      - event: mode_intergalactic_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_intergalactic_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_intergalactic_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_intergalactic_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_paulrevere_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_paulrevere_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_paulrevere_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_paulrevere_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_tripletrouble_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_tripletrouble_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_tripletrouble_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_tripletrouble_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_sabotage_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_sabotage_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_sabotage_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_sabotage_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_fingerlickingood_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_fingerlickingood_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_fingerlickingood_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_fingerlickingood_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_toomanyrappers_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_toomanyrappers_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_toomanyrappers_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_toomanyrappers_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_threemcsand1dj_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_threemcsand1dj_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_threemcsand1dj_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_threemcsand1dj_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_highplainsdrifter_stopped{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_highplainsdrifter_stopped{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: mode_highplainsdrifter_success{not device.achievements.wizard1.state=="completed"}
        action: jump
        value: 10
      - event: mode_highplainsdrifter_success{device.achievements.wizard1.state=="completed"}
        action: jump
        value: 20
      - event: multiball_makesomenoise_ended
        action: jump
        value: 20
      - event: scoop_hit{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and current_player.mode_blocking_flag==0 and current_player.girls_blocking_flag==0 and device.achievements.wizard1.state!="enabled" and device.counters.battery_charged_status.value>0}
        action: add
        value: -5
      - event: logicblock_battery_charged_status_updated{device.counters.battery_charged_status.value<0}
        action: jump
        value: 0



show_player:
  mode_batterycharger_started{current_player.ball==1}:
    battery_green:
      action: play
      loops: -1
  mode_batterycharger_started{current_player.ball!=1 and current_player.battery_charged_yesorno==1}:
    battery_green:
      action: play
      loops: -1
  mode_batterycharger_started{current_player.ball!=1 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value>10}:
    battery_red:
      action: play
      loops: -1
  mode_batterycharger_started{current_player.ball!=1 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value<11 and device.achievements.wizard1.state!="enabled"}:
    battery_yellow:
      action: play
      loops: -1
  battery_charged:
    battery_red:
      action: stop
    battery_yellow:
      action: stop
    battery_green:
      action: play
      loops: -1
  multiball_chcheckitout_started:
    battery_red:
      action: stop
    battery_yellow:
      action: stop
    battery_green:
      action: stop
  multiball_bodymovin_started:
    battery_red:
      action: stop
    battery_yellow:
      action: stop
    battery_green:
      action: stop
  mode_makesomenoise_started:
    battery_red:
      action: stop
    battery_yellow:
      action: stop
    battery_green:
      action: stop
  mode_girls_started:
    battery_red:
      action: stop
    battery_yellow:
      action: stop
    battery_green:
      action: stop
  carousel_item_selected:
    battery_green:
      action: stop
  multiball_chcheckitout_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==1 and device.achievements.wizard1.state!="enabled"}:
    battery_green:
      action: play
      loops: -1
  multiball_chcheckitout_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value<16 and device.achievements.wizard1.state!="enabled"}:
    battery_yellow:
      action: play
      loops: -1
  multiball_chcheckitout_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value>15 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_girls_stopped{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==1 and device.achievements.wizard1.state!="enabled"}:
    battery_green:
      action: play
      loops: -1
  mode_girls_stopped{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value<16 and device.achievements.wizard1.state!="enabled"}:
    battery_yellow:
      action: play
      loops: -1
  mode_girls_stopped{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value>15 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  multiball_bodymovin_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==1 and device.achievements.wizard1.state!="enabled"}:
    battery_green:
      action: play
      loops: -1
  multiball_bodymovin_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value<16 and device.achievements.wizard1.state!="enabled"}:
    battery_yellow:
      action: play
      loops: -1
  multiball_bodymovin_ended{current_player.mode_blocking_flag==0 and current_player.battery_charged_yesorno==0 and device.counters.battery_charged_status.value>15 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_intergalactic_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_intergalactic_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_paulrevere_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_paulrevere_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_tripletrouble_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_tripletrouble_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_sabotage_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_sabotage_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_fingerlickingood_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_fingerlickingood_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_toomanyrappers_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_toomanyrappers_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_threemcsand1dj_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_threemcsand1dj_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_highplainsdrifter_stopped{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_highplainsdrifter_success{current_player.bodymovin_multiball_blocking_flag==0 and current_player.chcheckitout_multiball_blocking_flag==0 and device.achievements.wizard1.state!="enabled"}:
    battery_red:
      action: play
      loops: -1
  mode_makesomenoise_stopped:
    battery_red:
      action: play
      loops: -1
  logicblock_battery_charged_status_updated{device.counters.battery_charged_status.value<16 and device.counters.battery_charged_status.value>0 and device.achievements.wizard1.state!="enabled" and device.counters.battery_charged_status.enabled==True}:
    battery_red:
      action:
        stop
    battery_yellow:
      action: play
      loops: -1
  achievement_wizard1_state_enabled:
    battery_green:
      action: stop
    battery_yellow:
      action: stop
    battery_red:
      action: stop


variable_player:
  logicblock_battery_charged_status_updated:
    charges_remaining_variable:
      int: device.counters.battery_charged_status.value * 1
      action: set


widget_player:
  battery_charged:
    charges_remaining:
      action: remove
  logicblock_battery_charged_status_updated{device.counters.battery_charged_status.value>0 and device.achievements.wizard1.state!="enabled" and device.counters.battery_charged_status.enabled==True}:
    charges_remaining:
      action: play
      slide: score_overlay
      priority: 901000
  achievement_wizard1_state_enabled{device.achievements.wizard1.state=="enabled"}:
    charges_remaining:
      action: remove
  mode_makesomenoise_stopped:
    charges_remaining:
      action: play
      slide: score_overlay
      priority: 901000
  ball_started{current_player.ball!=1 and device.counters.battery_charged_status.value>0 and device.achievements.wizard1.state!="enabled" and device.counters.battery_charged_status.enabled==True and current_player.battery_charged_yesorno==0}:
    charges_remaining:
      action: play
      slide: score_overlay
      priority: 901000
  ball_will_end:
    charges_remaining:
      action: remove
  mode_fingerlickingood_started:
    charges_remaining:
      action: remove
  mode_highplainsdrifter_started:
    charges_remaining:
      action: remove
  mode_intergalactic_started:
    charges_remaining:
      action: remove
  mode_makesomenoise_started:
    charges_remaining:
      action: remove
  mode_paulrevere_started:
    charges_remaining:
      action: remove
  mode_sabotage_started:
    charges_remaining:
      action: remove
  mode_threemcsand1dj_started:
    charges_remaining:
      action: remove
  mode_toomanyrappers_started:
    charges_remaining:
      action: remove
  mode_tripletrouble_started:
    charges_remaining:
      action: remove



sound_player:
  batterychargercallout1:
    batterycharger_callout1:
      action: play
      bus: voice
  batterychargercallout2:
    batterycharger_callout2:
      action: play
      bus: voice


random_event_player:
  scoop_hit{device.counters.battery_charged_status.enabled==True and device.counters.battery_charged_status.value>0 and device.achievements.wizard1.state!="enabled" and device.counters.completed_modes_count.value!=2}:
    events:
      - batterychargercallout1
      - batterychargercallout2
