#config_version=6
mode:
  start_events: ball_starting
  priority: 100

sequence_shots:
  left_orbit:
    switch_sequence: s_left_orbit, s_right_orbit
    sequence_timeout: 3s
  right_orbit:
    switch_sequence: s_right_orbit, s_left_orbit
    sequence_timeout: 3s
  inner_loop:
    switch_sequence: s_inner_orbit, s_right_orbit
    sequence_timeout: 2s
  right_ramp:
    switch_sequence: s_right_ramp
  left_ramp:
    switch_sequence: s_left_ramp
  pop_standup:
    switch_sequence: s_pop_standup
  upper_pop_standup:
    switch_sequence: s_upper_pop_standup
  scoop:
    switch_sequence: s_scoop
  captive_ball:
    switch_sequence: s_captive_ball
  three_bank_standup:
    switch_sequence: s_three_bank_standup
  spinner:
    switch_sequence: s_spinner
  pop1:
    switch_sequence: s_left_upper_pop
  pop2:
    switch_sequence: s_center_upper_pop
  pop3:
    switch_sequence: s_right_lower_pop
  bottom_drop:
    switch_sequence: s_three_bank_bottom
  middle_drop:
    switch_sequence: s_three_bank_middle
  top_drop:
    switch_sequence: s_three_bank_top
  tshirt_top_standup:
    switch_sequence: s_tshirt_top_standup
  tshirt_bottom_standup:
    switch_sequence: s_tshirt_bottom_standup



slide_player:
  mode_base_started:
    base:
      action: play
      priority: 5000
    score_overlay:
      action: play
      priority: 900000
    attract:
      action: remove
  mode_intergalactic_failed:
    intergalactic:
      action: remove
    base:
      action: play
      priority: 5000
    intergalacticfailed:
      action: play
      priority: 950000
      expire: 3s
  intergalactic_shot_5_done:
    intergalactic:
      action: remove
    base:
      action: play
      priority: 5000
    intergalacticfinish:
      action: play
      priority: 900000
      expire: 7s
  mode_paulrevere_stop:
    paulrevere:
      action: remove
    base:
      action: play
      priority: 5000
  mode_paulrevere_failed:
    paulrevere:
      action: remove
    base:
      action: play
      priority: 5000
  mode_paulrevere_success:
    paulrevere:
      action: remove
    base:
      action: play
      priority: 5000
    paulrevere_success:
      action: play
      priority: 850000
      expire: 3s
  mode_tripletrouble_stop:
    tripletrouble:
      action: remove
    tripletrouble_standups_counter:
      action: remove
    tripletrouble_final_shot_lit:
      action: remove
    base:
      action: play
      priority: 5000
  mode_tripletrouble_failed:
    tripletrouble:
      action: remove
    tripletrouble_standups_counter:
      action: remove
    tripletrouble_final_shot_lit:
      action: remove
    tripletroublefailed:
      action: play
      priority: 850000
      expire: 6s
    base:
      action: play
      priority: 5000
  mode_tripletrouble_success:
    tripletrouble:
      action: remove
    tripletrouble_final_shot_lit:
      action: remove
    base:
      action: play
      priority: 5000
    tripletroublefinish:
      action: play
      priority: 850000
      expire: 6s
  skill_success:
    skillshot_success_overlay:
      action: play
      priority: 850000
      expire: 2s
  multiball_chcheckitout_ended:
    multiball1:
      action: remove
    multiball2:
      action: remove
    multiball3:
      action: remove
    base:
      action: play
      priority: 5000
  ball_ending:
    multiball1:
      action: remove
    multiball2:
      action: remove
    multiball3:
      action: remove
    base:
      action: remove
    paulrevere:
      action: remove
    paulrevere_display_timer:
      action: remove
    tripletrouble:
      action: remove
    tripletrouble_display_timer:
      action: remove
    tripletrouble_standups_counter:
      action: remove
    tripletrouble_final_shot_lit:
      action: remove
    tripletroublefailed:
      action: remove
    tripletroublefinish:
      action: remove
    intergalactic:
      action: remove
    intergalacticfinish:
      action: remove
    intergalacticfailed:
      action: remove
    intergalactic_display_timer:
      action: remove
    score_overlay:
      action: remove
    current_mode_highlighted:
      action: remove
  play_base_video1:
    basevideo1:
      action: play
      priority: 5001
  play_base_video2:
    basevideo2:
      action: play
      priority: 5001
  play_base_video3:
    basevideo3:
      action: play
      priority: 5001
  play_base_video4:
    basevideo4:
      action: play
      priority: 5001
  mode_makesomenoise_stopped:
    base:
      action: play
      priority: 5000


sound_player:
  mode_carousel_started:
    base_game_random_music:
      action: play
      bus: music
      loops: 13
  drop_target_top_down:
    drop_sound_random:
      action: play
      bus: effects
      max_queue_time: 1s
  drop_target_middle_down:
    drop_sound_random:
      action: play
      bus: effects
      max_queue_time: 1s
  drop_target_bottom_down:
    drop_sound_random:
      action: play
      bus: effects
      max_queue_time: 1s
  spinner_hit:
    spinner_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  pop1_hit:
    pops_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  pop2_hit:
    pops_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  pop3_hit:
    pops_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  three_bank_standup_hit:
    standup_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  pop_standup_hit:
    standup_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  upper_pop_standup_hit:
    standup_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
  captive_ball_hit:
    captive_sound:
      action: play
      bus: effects
      max_queue_time: 500ms
      block: true
  mode_carousel_stopped:
    base_game_random_music:
      action: stop
      bus: music
  mode_paulrevere_stopped:
    paulrevere_music:
      action: stop
      bus: music
  mode_paulrevere_success{current_player.multiball_blocking_flag==0}:
    base_game_random_music:
      action: play
      bus: music
      loops: 14
  mode_paulrevere_success{current_player.multiball_blocking_flag==1}:
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  mode_paulrevere_failed{current_player.multiball_blocking_flag==0}: #or  slide_intergalacticfailed_removed
    base_game_random_music:
      action: play
      bus: music
      loops: 13
  mode_paulrevere_failed{current_player.multiball_blocking_flag==1}: #or  slide_intergalacticfailed_removed
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  mode_intergalactic_stopped:
    intergalacticmusic:
      action: stop
      bus: music
  mode_intergalactic_success{current_player.multiball_blocking_flag==0}:
    base_game_random_music:
      action: play
      bus: music
      loops: 14
  mode_intergalactic_success{current_player.multiball_blocking_flag==1}:
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  mode_intergalactic_failed{current_player.multiball_blocking_flag==0}: #or  slide_intergalacticfailed_removed
    base_game_random_music:
      action: play
      bus: music
      loops: 13
  mode_intergalactic_failed{current_player.multiball_blocking_flag==1}: #or  slide_intergalacticfailed_removed
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  multiball_chcheckitout_started{current_player.mode_blocking_flag==0}: #add player_ back in before mode_blocking_flags?
    base_game_random_music:
      action: stop
      bus: music
  multiball_chcheckitout_ended{current_player.mode_blocking_flag==0}:
    chcheckitoutmultiballmusic:
      action: stop
      bus: music
    base_game_random_music:
      action: play
      bus: music
      loops: 13
  mode_makesomenoise_stopped:
    makesomenoisemusic:
      action: stop
      bus: music
  mode_tripletrouble_stopped:
    tripletroublemusic:
      action: stop
      bus: music
  mode_tripletrouble_success{current_player.multiball_blocking_flag==0}:
    base_game_random_music:
      action: play
      bus: music
      loops: 14
  mode_tripletrouble_success{current_player.multiball_blocking_flag==1}:
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  mode_tripletrouble_failed{current_player.multiball_blocking_flag==0}: #or  slide_intergalacticfailed_removed
    base_game_random_music:
      action: play
      bus: music
      loops: 13
  mode_tripletrouble_failed{current_player.multiball_blocking_flag==1}: #or  slide_intergalacticfailed_removed
    chcheckitoutmultiballmusic:
      action: play
      bus: music
      loops: 5
  ball_ending:
    chcheckitoutmultiballmusic:
      action: stop
      bus: music
    base_game_random_music:
      action: stop
      bus: music
    paulrevere_music:
      action: stop
      bus: music
    intergalacticmusic:
      action: stop
      bus: music
    makesomenoisemusic:
      action: stop
      bus: music
    tripletroublemusic:
      action: stop
      bus: music


variable_player:
  s_right_inlane_active:
    score: 110
  s_left_inlane_active:
    score: 110
  s_right_outlane_active:
    score: 1110
  s_left_outlane_active:
    score: 1110
  s_left_slingshot_active:
    score: 10
  s_right_slingshot_active:
    score: 10
  s_right_lower_pop_active:
    score: 1110
  s_left_upper_pop_active:
    score: 1110
  s_center_upper_pop_active:
    score: 1110
  s_upper_pop_standup_active:
    score: 5010
  pop_standup_hit:
    score: 5010
  captive_ball_hit:
    score: 10010
  s_spinner_active:
    score: 1010
  s_three_bank_bottom_active:
    score: 2220
  s_three_bank_middle_active:
    score: 2220
  s_three_bank_top_active:
    score: 2220
  scoop_hit:
    score: 2310
  s_tshirt_top_standup_active:
    score: 5010
  s_tshirt_bottom_standup_active:
    score: 5010
  three_bank_standup_hit:
    score: 20010
  s_left_orbit_active:
    score: 110
  s_right_orbit_active:
    score: 110
  s_inner_orbit_active:
    score: 1010
  left_ramp_hit:
    score: 3010
  right_ramp_hit:
    score: 3010
  logicblock_drop_target_bank_counter_updated:
    drop_target_bank_counter_count:
      int: value
      action: set
  ball_started:
    multiball_blocking_flag:
      int: value
      action: set
    mode_blocking_flag:
      int: value
      action: set
    player_drop_target_bank_counter_count:
      int: 0
      action: set
  mode_intergalactic_stopped:
    mode_blocking_flag:
      int: 0
      action: set
  mode_paulrevere_stopped:
    mode_blocking_flag:
      int: 0
      action: set
  mode_makesomenoise_stopped:
    mode_blocking_flag:
      int: 0
      action: set
  mode_tripletrouble_stopped:
    mode_blocking_flag:
      int: 0
      action: set
  mode_intergalactic_started:
    mode_intergalactic_score:
      int: 0
      action: set
  mode_paulrevere_started:
    mode_paulrevere_score:
      int: 0
      action: set
  mode_makesomenoise_started:
    mode_makesomenoise_score:
      int: 0
      action: set
  mode_tripletrouble_started:
    mode_tripletrouble_score:
      int: 0
      action: set
  game_ended:
    game_just_played:
      int: 1
      action: set_machine


sequences:
  qualify_chcheckitout_multiball:
    events:
      - chcheckitout_multiball_qualified
    events_when_complete: drops_standup_start_multiball
    reset_on_complete: true #this could be a problem if multiballs are immediately lighting again too fast
    disable_on_complete: false
    reset_events: ball_started
  chcheckitout_multiball_ready:
    events:
      - three_bank_standup_hit
    enable_events: drops_standup_start_multiball
    events_when_complete: chcheckitout_start_multiball
    reset_on_complete: true
    disable_on_complete: false
    reset_events: ball_started

counters:
  drop_target_bank_counter:
    count_events: drop_target_bank_three_bank_down
    events_when_complete: chcheckitout_multiball_qualified
    starting_count: 0
    count_complete_value: 1
    count_interval: 1
    direction: up
    persist_state: false
    disable_on_complete: false
    reset_on_complete: false
    disable_events: multiball_chcheckitout_started, mode_makesomenoise_started
    enable_events: ball_started, mode_makesomenoise_stopped
    restart_events: multiball_chcheckitout_ended
    control_events:
      - event: reset_drop_target_bank_counter
        action: jump
        value: 0

event_player:
  multiball_chcheckitout_ended: reset_drop_target_bank_counter


random_event_player:
  multiball_chcheckitout_started:
    events:
      - play_chcheckitout_video1
      - play_chcheckitout_video2
      - play_chcheckitout_video3
  slide_base_created:
    events:
      - play_base_video1
      - play_base_video2
      - play_base_video3
      - play_base_video4