#config_version=6

mode:
  start_events: mode_base_started
  priority: 1000


multiballs:
  chcheckitout:
    ball_count: 3
    start_events: mode_chcheckitout_started
    shoot_again: 15s
    add_a_ball_events: three_bank_standup_hit
    reset_events: multiball_chcheckitout_ended
    enable_events: mode_chcheckitout_starting
  bodymovin:
    ball_count: 3
    start_events: mode_bodymovin_started
    shoot_again: 15s
    reset_events: multiball_bodymovin_ended
    enable_events: mode_bodymovin_starting
  makesomenoise:
    ball_count: 4
    start_events: ball_hold_makesomenoise_scoop_hold_balls_released
    shoot_again: 45s
    reset_events: multiball_makesomenoise_ended
    enable_events: mode_makesomenoise_starting


sound_player:
  multiball_chcheckitout_started:
    chcheckitout_start_callout:
      action: play
      bus: voice
      priority: 10000
  multiball_bodymovin_started:
    bodymovin_start_callout:
      action: play
      bus: voice
      priority: 10000

