#config_version=6

mode:
  start_events: bodymovin_start_multiball
  stop_events: multiball_bodymovin_ended
  priority: 10000


slide_player:
  mode_bodymovin_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
  bodymovinmusic1:
    bodymovin:
      action: play
      priority: 450000
  bodymovinmusic2:
    bodymovin:
      action: play
      priority: 450000


sound_player:
  bodymovinmusic1:
    bodymovinmultiballmusic1:
      action: replace
      bus: music
      loops: 5
  bodymovinmusic2:
    bodymovinmultiballmusic2:
      action: replace
      bus: music
      loops: 5
  bodymovin_jackpot_hit:
    jackpot_callout:
      action: play
      bus: voice
      max_queue_time: 1s
  bodymovin_superjackpot_hit:
    superjackpot_callout:
      action: play
      bus: voice
      max_queue_time: 1s


random_event_player:
  mode_bodymovin_started{current_player.mode_blocking_flag==0}:
    events:
      - bodymovinmusic1
      - bodymovinmusic2
  bodymovin_music_from_mode:
    events:
      - bodymovinmusic1
      - bodymovinmusic2


variable_player:
  mode_bodymovin_started:
    bodymovin_multiball_blocking_flag:
      int: 1
      action: set
    multiball_bodymovin_score:
      int: 0
      action: set
    bodymovin_multiball_qualified_flag:
      int: 0
      action: set
  bodymovin_jackpot_hit:
    score: 500000
    multiball_bodymovin_score: 500000
  bodymovin_superjackpot_hit:
    score: 2000000
    multiball_bodymovin_score: 2000000


accruals:
  completing_bodymovin_jackpots:
    events:
      - bodymovin_leftorbit_jackpot_hit
      - bodymovin_leftramp_jackpot_hit
      - bodymovin_rightramp_jackpot_hit
      - bodymovin_rightorbit_jackpot_hit
    events_when_complete: bodymovin_superjackpot_lit
    restart_events: bodymovin_superjackpot_hit


sequences:
  bodymovin_leftorbit_jackpot:
    events:
      - left_orbit_hit
#    enable_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
    events_when_complete: bodymovin_leftorbit_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: True
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
  bodymovin_leftramp_jackpot:
    events:
      - left_ramp_hit
#    enable_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
    events_when_complete: bodymovin_leftramp_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: True
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
  bodymovin_rightramp_jackpot:
    events:
      - right_ramp_hit
#    enable_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
    events_when_complete: bodymovin_rightramp_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: True
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
  bodymovin_rightorbit_jackpot:
    events:
      - right_orbit_hit
#    enable_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
    events_when_complete: bodymovin_rightorbit_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: True
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit
  bodymovin_superjackpot:
    events:
      - inner_loop_hit
#    enable_events: bodymovin_superjackpot_lit
    events_when_complete: bodymovin_superjackpot_hit
    reset_on_complete: True
    restart_events: bodymovin_superjackpot_lit


show_player:
  bodymovin_superjackpot_lit:
    bodymovin_inner_loop_shot:
      action: play
  bodymovin_superjackpot_hit:
    bodymovin_inner_loop_shot:
      action: stop
  mode_bodymovin_started:
    chcheckitout_lit_strobe:
      action: stop
  multiball_bodymovin_started:
    ball_save_show:
      action: play
      loops: -1
  multiball_bodymovin_shoot_again_ended:
    ball_save_show:
      action: stop


blinkenlight_player:
  mode_bodymovin_started:
    bl_leftorbit_arrow_led:
      color: 4CBB17
    bl_leftramp_arrow_led:
      color: 4CBB17
    bl_rightramp_arrow_led:
      color: 4CBB17
    bl_rightorbit_arrow_led:
      color: 4CBB17
    bl_captiveball_smallcircle_led: remove
  bodymovin_leftorbit_jackpot_hit:
    bl_leftorbit_arrow_led: remove
  bodymovin_leftramp_jackpot_hit:
    bl_leftramp_arrow_led: remove
  bodymovin_rightramp_jackpot_hit:
    bl_rightramp_arrow_led: remove
  bodymovin_rightorbit_jackpot_hit:
    bl_rightorbit_arrow_led: remove
  bodymovin_superjackpot_hit:
    bl_leftorbit_arrow_led:
      color: 4CBB17
    bl_leftramp_arrow_led:
      color: 4CBB17
    bl_rightramp_arrow_led:
      color: 4CBB17
    bl_rightorbit_arrow_led:
      color: 4CBB17

event_player:
  mode_paulrevere_success{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  mode_paulrevere_failed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_intergalacticfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_intergalacticfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_tripletroublefinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_tripletroublefailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_sabotagefinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_sabotagefailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_fingerlickingoodfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_fingerlickingoodfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_toomanyrappersfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_toomanyrappersfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_threemcsand1djfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_threemcsand1djfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_highplainsdrifterfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_highplainsdrifterfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode

