#config_version=6

mode:
  start_events: bodymovin_start_multiball
  stop_events: multiball_bodymovin_ended
  priority: 10000


slide_player:
  mode_bodymovin_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
  bodymovinmusic1:
    bodymovin:
      action: play
      priority: 450000
  bodymovinmusic2:
    bodymovin:
      action: play
      priority: 450000
  slide_bodymovin_created:
    bodymovin_round_slide:
      action: play
      priority: 1000001


sound_player:
  bodymovinmusic1:
    bodymovinmultiballmusic1:
      action: replace
      bus: music
      loops: 5
  bodymovinmusic2:
    bodymovinmultiballmusic2:
      action: replace
      bus: music
      loops: 5
  bodymovin_jackpot_hit:
    jackpot_callout:
      action: play
      bus: voice
      max_queue_time: 1s
  bodymovin_superjackpot_hit:
    superjackpot_callout:
      action: play
      bus: voice
      max_queue_time: 1s


random_event_player:
  mode_bodymovin_started{current_player.mode_blocking_flag==0}:
    events:
      - bodymovinmusic1
      - bodymovinmusic2
  bodymovin_music_from_mode:
    events:
      - bodymovinmusic1
      - bodymovinmusic2
  bodymovin_advance_super_jackpot_random:
    events:
      - bodymovin_advance_super_leftorbit
      - bodymovin_advance_super_leftramp
      - bodymovin_advance_super_captive
      - bodymovin_advance_super_innerloop
      - bodymovin_advance_super_rightramp
      - bodymovin_advance_super_rightorbit


variable_player:
  mode_bodymovin_started:
    bodymovin_multiball_blocking_flag:
      int: 1
      action: set
    multiball_bodymovin_score:
      int: 0
      action: set
    bodymovin_multiball_qualified_flag:
      int: 0
      action: set
    bodymovin_round:
      int: 1
      action: set
  bodymovin_jackpot_hit:
    score: 500000 * current_player.bodymovin_round * current_player.playfield_x
    multiball_bodymovin_score: 500000 * current_player.bodymovin_round * current_player.playfield_x
  bodymovin_superjackpot_hit:
    score: 2000000 * current_player.bodymovin_round * current_player.playfield_x
    multiball_bodymovin_score: 2000000 * current_player.bodymovin_round * current_player.playfield_x
    bodymovin_round: 1


accruals:
  completing_bodymovin_jackpots:
    events:
      - bodymovin_leftramp_jackpot_hit
      - bodymovin_rightramp_jackpot_hit
    events_when_complete: bodymovin_jackpots_complete
    restart_events: bodymovin_superjackpot_hit, bodymovin_relight_ramps


sequences:
  bodymovin_leftramp_jackpot:
    events:
      - left_ramp_hit
    events_when_complete: bodymovin_leftramp_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit, bodymovin_relight_ramps
  bodymovin_rightramp_jackpot:
    events:
      - right_ramp_hit
    events_when_complete: bodymovin_rightramp_jackpot_hit, bodymovin_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_bodymovin_started, bodymovin_superjackpot_hit, bodymovin_relight_ramps
  bodymovin_superjackpot:
    events:
      - bodymovin_roving_shot_lit_hit
    events_when_complete: bodymovin_superjackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: bodymovin_superjackpot_lit


timers:
  bodymovin_roam_right:
    start_value: 0
    end_value: 3
    control_events:
      - action: start
        event: bodymovin_superjackpot_lit
      - action: restart
        event: timer_bodymovin_roam_right_complete
      - action: pause
        event: bodymovin_superjackpot_hit


shot_profiles:
  bodymovin_roving_shot:
    advance_on_hit: False
    states:
      - name: off
      - name: lit
        show: flash_color
        show_tokens:
          color: red
        speed: 2
    loop: True


shots:
  bodymovin_leftorbit:
    hit_events: left_orbit_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_leftorbit
    show_tokens:
      led: l_leftorbit_arrow_led
  bodymovin_leftramp:
    hit_events: left_ramp_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_leftramp
    show_tokens:
      led: l_leftramp_arrow_led
  bodymovin_captiveball:
    hit_events: captive_ball_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_captive
    show_tokens:
      led: l_captiveball_smallcircle_led
  bodymovin_inner_loop:
    hit_events: inner_loop_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_innerloop
    show_tokens:
      led: l_innerloop_arrow_led
  bodymovin_rightramp:
    hit_events: right_ramp_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_rightramp
    show_tokens:
      led: l_rightramp_arrow_led
  bodymovin_rightorbit:
    hit_events: right_orbit_hit
    profile: bodymovin_roving_shot
    advance_events: advance_bodymovin_rightorbit
    show_tokens:
      led: l_rightorbit_arrow_led


shot_groups:
  bodymovin_roving_shot:
    shots: bodymovin_leftorbit, bodymovin_leftramp, bodymovin_inner_loop, bodymovin_captiveball, bodymovin_rightramp, bodymovin_rightorbit
    rotate_right_events: timer_bodymovin_roam_right_complete
    restart_events: bodymovin_superjackpot_lit
    enable_events: bodymovin_superjackpot_lit
    disable_events: bodymovin_superjackpot_hit


show_player:
  mode_bodymovin_started:
    chcheckitout_lit_strobe:
      action: stop
  multiball_bodymovin_started:
    ball_save_show:
      action: play
      loops: -1
  multiball_bodymovin_shoot_again_ended:
    ball_save_show:
      action: stop


blinkenlight_player:
  mode_bodymovin_started:
    bl_leftramp_arrow_led:
      color: 4CBB17
    bl_rightramp_arrow_led:
      color: 4CBB17
    bl_captiveball_smallcircle_led: remove
  bodymovin_leftramp_jackpot_hit:
    bl_leftramp_arrow_led: remove
  bodymovin_rightramp_jackpot_hit:
    bl_rightramp_arrow_led: remove
  bodymovin_superjackpot_hit:
    bl_leftramp_arrow_led:
      color: 4CBB17
    bl_rightramp_arrow_led:
      color: 4CBB17
  bodymovin_relight_ramps:
    bl_leftramp_arrow_led:
      color: 4CBB17
    bl_rightramp_arrow_led:
      color: 4CBB17


counters:
  bodymovin_jackpots_collected:
    count_events: bodymovin_jackpots_complete
    starting_count: 0
    count_interval: 1
    count_complete_value: 1 + (current_player.bodymovin_round - 1)
    direction: up
    persist_state: False
    control_events:
      - event: bodymovin_superjackpot_lit
        action: jump
        value: 0
    restart_events: bodymovin_superjackpot_hit
    events_when_complete: bodymovin_superjackpot_lit
    disable_on_complete: True
    reset_on_complete: False


event_player:
  slide_paulreverefinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_paulreverefailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_intergalacticfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_intergalacticfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_tripletroublefinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_tripletroublefailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_sabotagefinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_sabotagefailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_fingerlickingoodfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_fingerlickingoodfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_toomanyrappersfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_toomanyrappersfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_threemcsand1djfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_threemcsand1djfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_highplainsdrifterfinish_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  slide_highplainsdrifterfailed_removed{current_player.bodymovin_multiball_blocking_flag==1}: bodymovin_music_from_mode
  bodymovin_superjackpot_lit: bodymovin_advance_super_jackpot_random
  bodymovin_advance_super_leftorbit: advance_bodymovin_leftorbit
  bodymovin_advance_super_leftramp: advance_bodymovin_leftramp
  bodymovin_advance_super_captive: advance_bodymovin_captive
  bodymovin_advance_super_innerloop: advance_bodymovin_innerloop
  bodymovin_advance_super_rightramp: advance_bodymovin_rightramp
  bodymovin_advance_super_rightorbit: advance_bodymovin_rightorbit
  bodymovin_leftramp_jackpot_hit{device.sequences.bodymovin_rightramp_jackpot.completed==True and device.counters.bodymovin_jackpots_collected.completed==False and current_player.bodymovin_round>(device.counters.bodymovin_jackpots_collected.value + 1)}: bodymovin_relight_ramps
  bodymovin_rightramp_jackpot_hit{device.sequences.bodymovin_leftramp_jackpot.completed==True and device.counters.bodymovin_jackpots_collected.completed==False and current_player.bodymovin_round>(device.counters.bodymovin_jackpots_collected.value + 1)}: bodymovin_relight_ramps

