#config_version=6

mode_settings:
  display_delay_ms: 2.5s
  hurry_up_delay_ms: 0
  hurry_up_event: flipper_cancel
  bonus_entries:
    - entry: bonus_modes_played
      score: 100000
      player_score_entry: modes_played
      skip_if_negative: true
    - entry: bonus_modes_completed
      score: 250000
      player_score_entry: modes_completed
      skip_if_negative: true
    - entry: bonus_time_remaining
      score: 1000
      player_score_entry: mode_time_remaining_total
      skip_if_negative: true
    - entry: bonus_combos
      score: 25000
      player_score_entry: combos
      skip_if_negative: true


variable_player:
  mode_bonus_started:
    mode_time_remaining_total:
      int: current_player.intergalactic_time_remaining_variable_times_1 + current_player.paulrevere_time_remaining_variable_times_1 + current_player.tripletrouble_time_remaining_variable_times_1 + current_player.sabotage_time_remaining_variable_times_1 + current_player.fingerlickingood_time_remaining_variable_times_1 + current_player.toomanyrappers_time_remaining_variable_times_1
      action: set


slide_player:
  mode_bonus_started:
    bonus_start_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="bonus_modes_played"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="bonus_modes_completed"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="bonus_time_remaining"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: remove
    bonus_time_remaining:
      action: play
      priority: 1000000
  bonus_entry{entry=="bonus_combos"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: remove
    bonus_time_remaining:
      action: remove
    bonus_combos_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="subtotal"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: remove
    bonus_time_remaining:
      action: remove
    bonus_combos_slide:
      action: remove
    bonus_subtotal_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="multiplier"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: remove
    bonus_time_remaining:
      action: remove
    bonus_combos_slide:
      action: remove
    bonus_subtotal_slide:
      action: remove
    bonus_multiplier_slide:
      action: play
      priority: 1000000
  bonus_entry{entry=="total"}:
    bonus_start_slide:
      action: remove
    bonus_modes_played_slide:
      action: remove
    bonus_modes_completed_slide:
      action: remove
    bonus_time_remaining:
      action: remove
    bonus_combos_slide:
      action: remove
    bonus_subtotal_slide:
      action: remove
    bonus_multiplier_slide:
      action: remove
    bonus_total_slide:
      action: play
      priority: 1000000

sound_player:
  mode_bonus_started:
    base_game_random_music:
      action: stop
      bus: music
  slide_bonus_start_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_combos_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_modes_played_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_modes_completed_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_time_remaining_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_multiplier_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_subtotal_slide_active:
    bonus_sound_random:
      action: play
      bus: effects
  slide_bonus_total_slide_active:
    bonus_sound_random:
      action: play
      bus: effects

random_event_player:
  mode_bonus_started:
    - play_red_show
    - play_pink_show
    - play_blue_show
    - play_green_show
    - play_orange_show
    - play_purple_show
    - play_yellow_show
  bonus_entry:
    - play_red_show
    - play_pink_show
    - play_blue_show
    - play_green_show
    - play_orange_show
    - play_purple_show
    - play_yellow_show

show_player:
  play_red_show:
    bonus_count_show_red:
      action: play
      loops: 0
      priority: 1000
  play_blue_show:
    bonus_count_show_blue:
      action: play
      loops: 0
      priority: 1000
  play_green_show:
    bonus_count_show_green:
      action: play
      loops: 0
      priority: 1000
  play_yellow_show:
    bonus_count_show_yellow:
      action: play
      loops: 0
      priority: 1000
  play_orange_show:
    bonus_count_show_orange:
      action: play
      loops: 0
      priority: 1000
  play_pink_show:
    bonus_count_show_pink:
      action: play
      loops: 0
      priority: 1000
  play_purple_show:
    bonus_count_show_purple:
      action: play
      loops: 0
      priority: 1000
