#config_version=6

mode:
  start_events: chcheckitout_start_multiball
  stop_events: multiball_chcheckitout_ended
  priority: 10000

slide_player:
  mode_chcheckitout_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    basevideo5:
      action: remove
    basevideo6:
      action: remove
  play_chcheckitout_video1:
    multiball1:
      action: play
      priority: 450000
  play_chcheckitout_video2:
    multiball2:
      action: play
      priority: 450000
  play_chcheckitout_video3:
    multiball3:
      action: play
      priority: 450000


sound_player:
  mode_chcheckitout_started{current_player.mode_blocking_flag==0}:
    base_game_random_music:
      action: stop
      bus: music
  play_chcheckitout_video1:
    chcheckitoutmultiballmusic:
      action: replace
      bus: music
      loops: 3
  play_chcheckitout_video2:
    chcheckitoutmultiballmusicletterman:
      action: replace
      bus: music
      loops: 3
      volume: 1.2 db
  play_chcheckitout_video3:
    chcheckitoutmultiballmusicremix:
      action: replace
      bus: music
      loops: 3
  chcheckitout_jackpot_hit:
    jackpot_callout:
      action: load
      bus: voice
      max_queue_time: 1s
  chcheckitout_superjackpot_hit:
    superjackpot_callout:
      action: load
      bus: voice
      max_queue_time: 1s


variable_player:
  mode_chcheckitout_started:
    chcheckitout_multiball_blocking_flag:
      int: 1
      action: set
    multiball_chcheckitout_score:
      int: 0
      action: set
    chcheckitout_qualified_flag:
      int: 0
      action: set
    chcheckitout_multiplier:
      int: 1
      action: set
  chcheckitout_leftorbit_jackpot_hit:
    score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
    multiball_chcheckitout_score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  chcheckitout_leftramp_jackpot_hit:
    score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.left_ramp_multiplier * current_player.loop_shot_multiplier
    multiball_chcheckitout_score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.left_ramp_multiplier * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  chcheckitout_rightramp_jackpot_hit:
    score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.right_ramp_multiplier * current_player.loop_shot_multiplier
    multiball_chcheckitout_score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.right_ramp_multiplier * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  chcheckitout_rightorbit_jackpot_hit:
    score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.right_orbit_multiplier * current_player.loop_shot_multiplier
    multiball_chcheckitout_score: 500000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.right_orbit_multiplier * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  chcheckitout_superjackpot_hit:
    score: 2000000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.upper_loop_multiplier * current_player.loop_shot_multiplier
    multiball_chcheckitout_score: 2000000 * current_player.chcheckitout_multiplier * current_player.playfield_x * current_player.upper_loop_multiplier * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  drop_target_bank_three_bank_down:
    chcheckitout_multiplier: 1
  right_inlane_hit:
    score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  left_inlane_hit:
    score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  right_outlane_hit:
    score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  left_outlane_hit:
    score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  s_left_slingshot_active:
    score: 10 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 10 * current_player.playfield_x * current_player.chcheckitout_multiplier
  s_right_slingshot_active:
    score: 10 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 10 * current_player.playfield_x * current_player.chcheckitout_multiplier
  pop1_hit:
    score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  pop2_hit:
    score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  pop3_hit:
    score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 1110 * current_player.playfield_x * current_player.chcheckitout_multiplier
  upper_pop_standup_hit:
    score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  pop_standup_hit:
    score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  captive_ball_hit:
    score: 10010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 10010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  spinner_hit:
    score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
    multiball_chcheckitout_score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
  bottom_drop_hit:
    score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
  middle_drop_hit:
    score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
  top_drop_hit:
    score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 2220 * current_player.playfield_x * current_player.chcheckitout_multiplier
  scoop_hit:
    score: 2310 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.scoop_multiplier
    multiball_chcheckitout_score: 2310 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.scoop_multiplier
  tshirt_top_standup_hit:
    score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  tshirt_bottom_standup_hit:
    score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 5010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  three_bank_standup_hit:
    score: 20010 * current_player.playfield_x * current_player.chcheckitout_multiplier
    multiball_chcheckitout_score: 20010 * current_player.playfield_x * current_player.chcheckitout_multiplier
  s_left_orbit_active:
    score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
    multiball_chcheckitout_score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
  s_right_orbit_active:
    score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_orbit_multiplier
    multiball_chcheckitout_score: 110 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_orbit_multiplier
  s_inner_orbit_active:
    score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.upper_loop_multiplier
    multiball_chcheckitout_score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.upper_loop_multiplier
  left_ramp_hit:
    score: 3010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_ramp_multiplier
    multiball_chcheckitout_score: 3010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_ramp_multiplier
  right_ramp_hit:
    score: 3010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_ramp_multiplier
    multiball_chcheckitout_score: 3010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_ramp_multiplier
  left_orbit_hit:
    score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
    multiball_chcheckitout_score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.left_orbit_multiplier
  right_orbit_hit:
    score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_orbit_multiplier
    multiball_chcheckitout_score: 1010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.right_orbit_multiplier
  inner_loop_hit:
    score: 2010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.upper_loop_multiplier
    multiball_chcheckitout_score: 2010 * current_player.playfield_x * current_player.chcheckitout_multiplier * current_player.upper_loop_multiplier


accruals:
  completing_chcheckitout_jackpots:
    events:
      - chcheckitout_leftorbit_jackpot_hit
      - chcheckitout_leftramp_jackpot_hit
      - chcheckitout_rightramp_jackpot_hit
      - chcheckitout_rightorbit_jackpot_hit
    events_when_complete: chcheckitout_superjackpot_lit
    restart_events: chcheckitout_superjackpot_hit


sequences:
  chcheckitout_leftorbit_jackpot:
    events:
      - left_orbit_hit
    events_when_complete: chcheckitout_leftorbit_jackpot_hit, chcheckitout_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_chcheckitout_started, chcheckitout_superjackpot_hit
  chcheckitout_leftramp_jackpot:
    events:
      - left_ramp_hit
    events_when_complete: chcheckitout_leftramp_jackpot_hit, chcheckitout_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_chcheckitout_started, chcheckitout_superjackpot_hit
  chcheckitout_rightramp_jackpot:
    events:
      - right_ramp_hit
    events_when_complete: chcheckitout_rightramp_jackpot_hit, chcheckitout_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_chcheckitout_started, chcheckitout_superjackpot_hit
  chcheckitout_rightorbit_jackpot:
    events:
      - right_orbit_hit
    events_when_complete: chcheckitout_rightorbit_jackpot_hit, chcheckitout_jackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: multiball_chcheckitout_started, chcheckitout_superjackpot_hit
  chcheckitout_superjackpot:
    events:
      - inner_loop_hit
    events_when_complete: chcheckitout_superjackpot_hit
    reset_on_complete: False
    disable_on_complete: True
    start_enabled: False
    restart_events: chcheckitout_superjackpot_lit


show_player:
  multiball_chcheckitout_started:
    ball_save_show:
      action: play
      loops: -1
  multiball_chcheckitout_shoot_again_ended:
    ball_save_show:
      action: stop
  chcheckitout_superjackpot_lit:
    chcheckitout_inner_loop_shot:
      action: play
  chcheckitout_superjackpot_hit:
    chcheckitout_inner_loop_shot:
      action: stop


blinkenlight_player:
  mode_chcheckitout_started:
    bl_leftorbit_arrow_led:
      color: red
    bl_leftramp_arrow_led:
      color: red
    bl_rightramp_arrow_led:
      color: red
    bl_rightorbit_arrow_led:
      color: red
  chcheckitout_leftorbit_jackpot_hit:
    bl_leftorbit_arrow_led: remove
  chcheckitout_leftramp_jackpot_hit:
    bl_leftramp_arrow_led: remove
  chcheckitout_rightramp_jackpot_hit:
    bl_rightramp_arrow_led: remove
  chcheckitout_rightorbit_jackpot_hit:
    bl_rightorbit_arrow_led: remove
  chcheckitout_superjackpot_hit:
    bl_leftorbit_arrow_led:
      color: red
    bl_leftramp_arrow_led:
      color: red
    bl_rightramp_arrow_led:
      color: red
    bl_rightorbit_arrow_led:
      color: red


random_event_player:
  mode_chcheckitout_started{current_player.mode_blocking_flag==0}:
    events:
      - play_chcheckitout_video1
      - play_chcheckitout_video2
      - play_chcheckitout_video3
    force_all: False
    force_different: False
  chcheckitout_music_from_mode:
    events:
      - play_chcheckitout_video1
      - play_chcheckitout_video2
      - play_chcheckitout_video3
    force_all: False
    force_different: False


event_player:
  slide_paulreverefinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_paulreverefailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_intergalacticfinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_intergalacticfailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_tripletroublefinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_tripletroublefailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_sabotagefinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_sabotagefailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_fingerlickingoodfinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_fingerlickingoodfailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_toomanyrappersfinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_toomanyrappersfailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_threemcsand1djfinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_threemcsand1djfailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_highplainsdrifterfinish_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  slide_highplainsdrifterfailed_removed{current_player.chcheckitout_multiball_blocking_flag==1}: chcheckitout_music_from_mode
  s_right_orbit_active{device.diverters.up_post.active==False and device.sequences.chcheckitout_superjackpot.enabled==True}: uppost_up
  inner_loop_hit: uppost_down

