#config_version=6

mode:
  start_events: carousel_item_selected{item=="tripletrouble"}
  stop_events: mode_tripletrouble_stop, mode_tripletrouble_failed, mode_tripletrouble_success, ball_will_end
  priority: 1001


counters:
  tripletrouble_standups_counter:
    count_events: pop_standup_hit, upper_pop_standup_hit, three_bank_standup_hit, s_tshirt_top_standup_active, s_tshirt_bottom_standup_active, captive_ball_hit
    events_when_complete: tripletrouble_standups_counter_complete
    starting_count: 7
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: False
    disable_on_complete: False
    reset_on_complete: False
    disable_events: mode_tripletrouble_ended
    enable_events: mode_tripletrouble_started
    restart_events: mode_tripletrouble_started, tripletrouble_final_shot_hit
    control_events:
      - event: reset_tripletrouble_standups_counter
        action: jump
        value: 7


sequences:
  tripletrouble_shot_1:
    events:
      - tripletrouble_standups_counter_complete
    events_when_complete: tripletrouble_shot_1_done
    reset_on_complete: False
  tripletrouble_shot_2:
    events:
      - scoop_hit
    enable_events: tripletrouble_shot_1_done
    events_when_complete: tripletrouble_final_shot_hit, mode_tripletrouble_stop
    reset_on_complete: False


variable_player:
  tripletrouble_shot_1_done:
    score: 5000000 * current_player.playfield_x
    mode_tripletrouble_score: 5000000 * current_player.playfield_x
  tripletrouble_final_shot_hit:
    score: 10000000 * current_player.playfield_x * current_player.loop_shot_multiplier
    mode_tripletrouble_score: 10000000 * current_player.playfield_x * current_player.loop_shot_multiplier
    loop_shot_multiplier:
      int: 1
      action: set
  logicblock_tripletrouble_standups_counter_hit:
    score: 500000 * current_player.playfield_x
    mode_tripletrouble_score: 500000 * current_player.playfield_x
    tripletrouble_standups_remaining:
      int: -1
      action: add
  timer_tripletrouble_intro_show_tick:
    tripletrouble_intro_show_variable_times_100:
      int: device.timers.tripletrouble_intro_show.ticks * 100
      action: set
  mode_tripletrouble_started:
    mode_blocking_flag:
      int: 1
      action: set
    tripletrouble_standups_remaining:
      int: 7
      action: set
  timer_tripletrouble_time_remaining_tick:
    tripletrouble_time_remaining_variable_times_1:
      int: device.timers.tripletrouble_time_remaining.ticks * 1
      action: set
  right_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 110 * current_player.playfield_x
  left_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 110 * current_player.playfield_x
  right_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 1110 * current_player.playfield_x
  left_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 1110 * current_player.playfield_x
  s_left_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 10 * current_player.playfield_x
  s_right_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 10 * current_player.playfield_x
  pop1_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 1110 * current_player.playfield_x
  pop2_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 1110 * current_player.playfield_x
  pop3_hit:
    score: 
      int: 1110 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 1110 * current_player.playfield_x
  upper_pop_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 5010 * current_player.playfield_x
  pop_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 5010 * current_player.playfield_x
  captive_ball_hit:
    score: 
      int: 250000 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 250000 * current_player.playfield_x
  spinner_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_tripletrouble_score: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
  bottom_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 2220 * current_player.playfield_x
  middle_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 2220 * current_player.playfield_x
  top_drop_hit:
    score: 
      int: 2220 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 2220 * current_player.playfield_x
  scoop_hit:
    score: 
      int: 2310 * current_player.playfield_x * current_player.scoop_multiplier
      block: True
    mode_tripletrouble_score: 2310 * current_player.playfield_x * current_player.scoop_multiplier
  tshirt_top_standup_hit:
    score: 
      int: 250000 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 250000 * current_player.playfield_x
  tshirt_bottom_standup_hit:
    score: 
      int: 250000 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 250000 * current_player.playfield_x
  three_bank_standup_hit:
    score: 
      int: 20010 * current_player.playfield_x
      block: True
    mode_tripletrouble_score: 20010 * current_player.playfield_x
  s_left_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_tripletrouble_score: 110 * current_player.playfield_x * current_player.left_orbit_multiplier
  s_right_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.right_orbit_multiplier
      block: True
    mode_tripletrouble_score: 110 * current_player.playfield_x * current_player.right_orbit_multiplier
  s_inner_orbit_active:
    score: 
      int: 1010 * current_player.playfield_x * current_player.upper_loop_multiplier
      block: True
    mode_tripletrouble_score: 1010 * current_player.playfield_x * current_player.upper_loop_multiplier
  left_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.left_ramp_multiplier
      block: True
    mode_tripletrouble_score: 3010 * current_player.playfield_x * current_player.left_ramp_multiplier
  right_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.right_ramp_multiplier
      block: True
    mode_tripletrouble_score: 3010 * current_player.playfield_x * current_player.right_ramp_multiplier
  left_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
      block: True
    mode_tripletrouble_score: 1010 * current_player.playfield_x * current_player.left_orbit_multiplier
  right_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.right_orbit_multiplier
      block: True
    mode_tripletrouble_score: 1010 * current_player.playfield_x * current_player.right_orbit_multiplier
  inner_loop_hit:
    score: 
      int: 2010 * current_player.playfield_x * current_player.upper_loop_multiplier
      block: True
    mode_tripletrouble_score: 2010 * current_player.playfield_x * current_player.upper_loop_multiplier


slide_player:
  mode_tripletrouble_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    basevideo5:
      action: remove
    basevideo6:
      action: remove
    tripletrouble:
      action: play
      priority: 500000
    tripletrouble_instructions:
      action: play
      priority: 500001
      expire: 5s
  flipper_cancel:
    tripletrouble_instructions:
      action: remove
  timer_tripletrouble_intro_show_complete:
    tripletrouble_standups_counter:
      action: play
      priority: 800000
    tripletrouble_display_timer:
      action: play
      priority: 1000000
  tripletrouble_shot_1_done:
    tripletrouble_standups_counter:
      action: remove
    tripletrouble_final_shot_lit:
      action: play
      priority: 800000
  tripletrouble_final_shot_hit:
    tripletrouble_final_shot_lit:
      action: remove


sound_player:
  mode_tripletrouble_started:
    tripletroublemusic:
      action: play
      bus: music
  logicblock_tripletrouble_standups_counter_hit:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  tripletrouble_final_shot_hit:
    success_finish:
      action: play
      bus: effects
      max_queue_time: 1s
  tencallout1:
    ten_callout1:
      action: load
      bus: voice
      max_queue_time: 1s
  tencallout2:
    ten_callout2:
      action: load
      bus: voice
      max_queue_time: 1s
  tencallout3:
    ten_callout3:
      action: load
      bus: voice
      max_queue_time: 1s


random_event_player:
  timer_tripletrouble_time_remaining_tick{current_player.tripletrouble_time_remaining_variable_times_1==10}:
    events:
      - tencallout1
      - tencallout2
      - tencallout3


ball_holds:
  tripletrouble_scoop_hold:
    balls_to_hold: 1
    hold_devices: bd_scoop
    enable_events: mode_tripletrouble_started
    disable_events: timer_tripletrouble_intro_show_complete
    release_one_events: timer_tripletrouble_intro_show_complete

timers:
  tripletrouble_intro_show:
    start_value: 0
    end_value: 5
    control_events:
      - action: start
        event: mode_tripletrouble_started
      - action: jump
        value: 5
        event: flipper_cancel{device.ball_holds.tripletrouble_scoop_hold.balls_held==1}
  tripletrouble_time_remaining:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_tripletrouble_intro_show_complete
      - action: pause
        event: tripletrouble_final_shot_hit
      - action: reset
        event: mode_tripletrouble_started
      - action: add
        value: 5
        event: add_tripletrouble_time_5s
      - action: add
        value: 15
        event: add_tripletrouble_time_15s


event_player:
  timer_tripletrouble_time_remaining_complete: mode_tripletrouble_failed
  tripletrouble_final_shot_hit: mode_tripletrouble_success
  pop_standup_hit: add_tripletrouble_time_15s
  upper_pop_standup_hit: add_tripletrouble_time_5s
  three_bank_standup_hit: add_tripletrouble_time_5s
  tshirt_top_standup_hit: add_tripletrouble_time_5s
  tshirt_bottom_standup_hit: add_tripletrouble_time_5s
  s_right_orbit_active{device.diverters.up_post.active==False}: uppost_up
  s_left_orbit_active{device.diverters.up_post.active==False and device.sequences.tripletrouble_shot_2.enabled==True}: uppost_up
  inner_loop_hit: uppost_down


shot_profiles:
  tripletrouble_shot:
    advance_on_hit: False
    states:
      - name: "off"
    loop: False


show_player:
  tripletrouble_shot_1_done:
    tripletrouble_final_shot:
      action: play
      loops: -1
  mode_tripletrouble_started:
    tripletrouble_backboard_show:
      action: play
      loops: -1
    tripletrouble_pops_show:
      action: play
      loops: -1
    tripletrouble_stadium_intro_lights:
      action: play
      loops: -1
  timer_tripletrouble_intro_show_complete:
    tripletrouble_stadium_intro_lights:
      action: stop


blinkenlight_player:
  timer_tripletrouble_intro_show_complete:
    bl_lowerrightstandup_circle_led:
      color: 32CD32 #lime green 75%
    bl_dropstandup_flasher_led:
      color: 32CD32 #lime green 75%
    bl_upperpop_smallarrow_led:
      color: 32CD32 #lime green 75%
    bl_tshirttopcircle_led:
      color: 32CD32 #lime green 75%
    bl_tshirtbottomcircle_led:
      color: 32CD32 #lime green 75%
    bl_captiveball_smallcircle_led:
      color: 32CD32 #lime green 75%
  tripletrouble_shot_1_done:
    bl_lowerrightstandup_circle_led: remove
    bl_dropstandup_flasher_led: remove
    bl_upperpop_smallarrow_led: remove
    bl_tshirttopcircle_led: remove
    bl_tshirtbottomcircle_led: remove
    bl_captiveball_smallcircle_led: remove

