#config_version=6

# mike is using this for the numbers
# https://fastpinball.com/cookbook/lower-third/
# https://fastpinball.com/mpf/config/net/

#v0.33

hardware:
  platform: fast
  driverboards: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1
      "3208":
        model: FP-I/O-3208
        order: 2
      "0804":
        model: FP-I/O-0804
        order: 3
      "0804b":
        model: FP-I/O-0804
        order: 4

  exp:
    boards:
      lightboard:
        model: FP-EXP-0081

  aud:
    port: auto
    debug: false

    main_amp_enabled: true
    sub_amp_enabled: true
    headphones_amp_enabled: true

    main_steps: 10
    sub_steps: 10
    headphones_steps: 10

    default_main_volume: 80
    default_sub_volume: 80
    default_headphones_volume: 60

    persist_volume_settings: true

    max_hw_volume_main: 100
    max_hw_volume_sub: 100
    max_hw_volume_headphones: 100

    main_levels_list: None
    sub_levels_list: None
    headphones_levels_list: None

    link_sub_to_main: true
    link_headphones_to_main: true

    headphones_level: line
    mute_speakers_with_headphones: true


displays:
  window:
    width: 1920
    height: 1080

slide_player:
  init_done:
    loading:
      action: play

config:
  - coils.yaml
  - switches.yaml
  - lights.yaml

machine_vars:
  game_just_played:
    initial_value: 0
    persist: False
    value_type: int


playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger
    enable_ball_search: false

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
  top_right_flipper:
    main_coil: c_flipper_top_right_main
    hold_coil: c_flipper_top_right_hold
    activation_switch: s_top_right_flipper

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_coil: c_plunger
    eject_timeouts: 3s
  bd_scoop:
    ball_switches: s_scoop
    eject_coil: c_scoop_eject
    eject_timeouts: 3s

ball_saves:
  default:
    active_time: 5s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: ball_out
    auto_launch: true
    balls_to_save: -1

modes:
  - base
  - attract
  - skill_shot
  - multiball
  - carousel
  - intergalactic
  - paulrevere
  - service
  - makesomenoise
  - tilt
  - tripletrouble
  - bonus
  - combos


settings:
  replay_score:
    label: Replay Score
    values:
      500000: "500000 (default)"
      1000000: "1000000"
      1500000: "1500000"
    default: 500000
    key_type: int
    sort: 100
  warnings_to_tilt:
    label: Number of tilt warnings
    values:
      0: "no warnings"
      1: "1"
      2: "2"
      3: "3"
      5: "5"
      10: "10"
    default: 3
    key_type: int
    sort: 600
  settle_time:
    label: Time to wait on tilt to settle bob
    values:
      3000: "3s"
      5000: "5s"
      10000: "10s"
    default: 5000
    key_type: int
    sort: 610
  multiple_hit_window:
    label: Tilt sensitivity
    values:
      150: "Sensitive"
      300: "Normal"
      500: "Insensitive"
      1000: "Very Insensitive"
    default: 300
    key_type: int
    sort: 620


event_player:
  machine_reset_phase_2:
    game_just_played:
      action: set_machine
      int: 0


variable_player:
  game_started:
    game_just_played:
      action: set_machine
      int: 1

shot_profiles:
  lit_mode_shot_profile:
    states:
      - name: flashing
        show: flash
      - name: unlit
        show: off
    loop: false

keyboard:
  s:
    switch: s_start
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  p:
    switch: s_plunger
    toggle: true
  m:
    switch: s_scoop
    toggle: true
  b:
    switch: s_right_lower_pop
  n:
    switch: s_center_upper_pop
  u:
    switch: s_three_bank_bottom
    toggle: true
  i:
    switch: s_three_bank_middle
    toggle: true
  o:
    switch: s_three_bank_top
    toggle: true
  y:
    switch: s_three_bank_standup
  d:
    switch: s_left_flipper
  f:
    switch: s_right_flipper
  q:
    switch: s_service_esc
  w:
    switch: s_service_down
  e:
    switch: s_service_up
  r:
    switch: s_service_enter

