#config_version=6

lights:
  l_leftorbit_arrow_led:
    number: lightboard-4-7
    subtype: led
    type: rgb
    label: "Left Orbit Arrow"
  l_leftramp_arrow_led:
    number: lightboard-3-1
    subtype: led
    type: rgb
    label: "Left Ramp Arrow"
  l_innerloop_arrow_led:
    number: lightboard-4-6
    subtype: led
    type: rgb
    label: "Inner Loop Arrow"
  l_rightramp_arrow_led:
    number: lightboard-8-7
    subtype: led
    type: rgb
    label: "Right Ramp Arrow"
  l_rightorbit_arrow_led:
    number: lightboard-8-8
    subtype: led
    type: rgb
    label: "Right Orbit Arrow"
  l_lowerrightstandup_circle_led:
    number: lightboard-2-1
    subtype: led
    type: rgb
    label: "Lower Right Standup Circle"
  l_upperpop_smallarrow_led:
    number: lightboard-4-2
    subtype: led
    type: rgb
    label: "Upper Pops Standup Circle"
  l_captiveball_smallcircle_led:
    number: lightboard-4-5
    subtype: led
    type: rgb
    label: "Captive Ball Arrow"
  l_lowerdrop_circle_led:
    number: lightboard-4-15
    subtype: led
    type: rgb
    label: "Lower Drop Rectangle"
  l_middledrop_circle_led:
    number: lightboard-4-14
    subtype: led
    type: rgb
    label: "Middle Drop Rectangle"
  l_upperdrop_circle_led:
    number: lightboard-4-13
    subtype: led
    type: rgb
    label: "Upper Drop Rectangle"
  l_dropstandup_flasher_led:
    number: lightboard-4-20
    subtype: led
    type: rgb
    label: "Behind Drops Standup Flasher"
    fade_ms: 500
  l_upperleftpop_inside_led:
    number: lightboard-6-1
    subtype: led
    type: rgb
    label: "Upper Left Pop Inside"
  l_uppercenterpop_inside_led:
    number: lightboard-6-2
    subtype: led
    type: rgb
    label: "Upper Right Pop Inside"
  l_lowerrightpop_inside_led:
    number: lightboard-2-10
    subtype: led
    type: rgb
    label: "Lower Right Pop Inside 1"
  l_lowerrightpop_inside2_led:
    number: lightboard-2-11
    subtype: led
    type: rgb
    label: "Lower Right Pop Inside 2"
  l_dropbank_rectangle_led:
    number: lightboard-4-12
    subtype: led
    type: rgb
    label: "Drops 2x Scoring Square"
  l_leftoutlane_circle_led:
    number: lightboard-4-19
    subtype: led
    type: rgb
    label: "Left Outlane Circle"
  l_leftinlane_circle_led:
    number: lightboard-4-16
    subtype: led
    type: rgb
    label: "Left Inlane Circle"
  l_rightinlane_circle_led:
    number: lightboard-2-8
    subtype: led
    type: rgb
    label: "Right Inlane Circle"
  l_rightoutlane_circle_led:
    number: lightboard-2-9
    subtype: led
    type: rgb
    label: "Right Outlane Circle"
  l_ballsave_circle_led:
    number: lightboard-3-18
    subtype: led
    type: rgb
    label: "Ball Save Circle"
  l_leftorbitcombo_circle_led:
    number: lightboard-4-8
    subtype: led
    type: rgb
    label: "Left Orbit Combo Circle"
  l_leftrampcombo_circle_led:
    number: lightboard-3-2
    subtype: led
    type: rgb
    label: "Left Ramp Combo Circle"
  l_innerloopcombo_circle_led:
    number: lightboard-4-4
    subtype: led
    type: rgb
    label: "Upper Loop Combo Circle"
  l_rightrampcombo_circle_led:
    number: lightboard-8-6
    subtype: led
    type: rgb
    label: "Right Ramp Combo Circle"
  l_rightorbitcombo_circle_led:
    number: lightboard-8-9
    subtype: led
    type: rgb
    label: "Right Orbit Combo Circle"
  l_scoopmode_square_led:
    number: lightboard-8-1
    subtype: led
    type: rgb
    label: "Scoop Rectangle - Mixmaster Mike"
    fade_ms: 500
  l_scoopmode_circle2_led:
    number: lightboard-8-2
    subtype: led
    type: rgb
    default_on_color: FFFF00
    label: "Scoop Extra Ball Circle"
  l_scoopcombo_circle_led:
    number: lightboard-8-3
    subtype: led
    type: rgb
    label: "Scoop Combo Circle"
  l_scoop_arrow_led:
    number: lightboard-8-4
    subtype: led
    type: rgb
    label: "Scoop Arrow"
  l_leftorbitbattery_rectangle_led:
    number: lightboard-4-11
    subtype: led
    type: rgb
    label: "Spinner Battery Rectangle"
    fade_ms: 500
  l_modeindicator1_rectangle_led:
    number: lightboard-3-9
    subtype: led
    type: rgb
    label: "Mode Rectangle 1 - Intergalactic"
  l_modeindicator2_rectangle_led:
    number: lightboard-3-8
    subtype: led
    type: rgb
    label: "Mode Rectangle 2 - Paul Revere"
  l_modeindicator3_rectangle_led:
    number: lightboard-2-4
    subtype: led
    type: rgb
    label: "Mode Rectangle 3 - Triple Trouble"
  l_modeindicator4_rectangle_led:
    number: lightboard-2-5
    subtype: led
    type: rgb
    label: "Mode Rectangle 4 - Sabotage"
  l_modeindicator5_rectangle_led:
    number: lightboard-3-13
    subtype: led
    type: rgb
    label: "Mode Rectangle 5 - Finger Lickin Good"
  l_modeindicator6_rectangle_led:
    number: lightboard-3-14
    subtype: led
    type: rgb
    label: "Mode Rectangle 6 - Too Many Rappers"
  l_modeindicator7_rectangle_led:
    number: lightboard-3-15
    subtype: led
    type: rgb
    label: "Mode Rectangle 7 - 3 MCs and One DJ"
  l_modeindicator8_rectangle_led:
    number: lightboard-3-16
    subtype: led
    type: rgb
    label: "Mode Rectangle 8 - High Plains Drifter"
  l_wizardindicator_rectangle_led:
    number: lightboard-3-17
    subtype: led
    type: rgb
    label: "Wizard Bottom Square - Sure Shot"
  l_wizardindicator2_rectangle_led:
    number: lightboard-3-7
    subtype: led
    type: rgb
    label: "Wizard Top Square - Make Some Noise"
  l_wizardindicator3_rectangle_led:
    number: lightboard-3-11
    subtype: led
    type: rgb
    label: "Wizard Middle Square - Bodhi Vow"
  l_supercircle1_led:
    number: lightboard-3-4
    subtype: led
    type: rgb
    label: "Super Circle 1 - Standups"
    fade_ms: 500
  l_supercircle2_led:
    number: lightboard-3-5
    subtype: led
    type: rgb
    label: "Super Circle 2 - Spins"
    fade_ms: 500
  l_supercircle3_led:
    number: lightboard-3-6
    subtype: led
    type: rgb
    label: "Super Circle 3 - Pops"
    fade_ms: 500
  l_supercircle4_led:
    number: lightboard-2-2
    subtype: led
    type: rgb
    label: "Super Circle 4 - Drops"
    fade_ms: 500
  l_supercircle5_led:
    number: lightboard-2-3
    subtype: led
    type: rgb
    label: "Super Circle 5 - Combos"
    fade_ms: 500
  l_cassetteleft_led:
    number: lightboard-3-12
    subtype: led
    type: rgb
    label: "Cassette Left Mini Circle"
  l_cassetteright_led:
    number: lightboard-3-10
    subtype: led
    type: rgb
    label: "Cassette Right Mini Circle"
  l_leftramprectangle_led:
    number: lightboard-3-3
    subtype: led
    type: rgb
    label: "Left Ramp Rectangle - Mike D"
    fade_ms: 500
  l_rightramprectangle_led:
    number: lightboard-8-5
    subtype: led
    type: rgb
    label: "Right Ramp Rectangle - Ad Roc"
    fade_ms: 500
  l_rightorbitrectangle_led:
    number: lightboard-8-10
    subtype: led
    type: rgb
    label: "Right Orbit Rectangle - DJ Hurricane"
    fade_ms: 500
  l_tshirttopcircle_led:
    number: lightboard-4-3
    subtype: led
    type: rgb
    label: "T-Shirt Top Circle"
  l_tshirtbottomcircle_led:
    number: lightboard-4-1
    subtype: led
    type: rgb
    label: "T-Shirt Bottom Circle"
  l_leftorbit_rectangle_led:
    number: lightboard-4-9
    subtype: led
    type: rgb
    label: "Left Orbit Rectangle - MCA"
    fade_ms: 500
  l_leftsling_uppergi_led:
    number: lightboard-4-17
    subtype: led
    type: grb
    label: "Left Sling Upper GI"
  l_leftsling_lowergi_led:
    number: lightboard-4-18
    subtype: led
    type: grb
    label: "Left Sling Lower GI"
  l_rightsling_uppergi_led:
    number: lightboard-2-6
    subtype: led
    type: grb
    label: "Right Sling Upper GI"
  l_rightsling_lowergi_led:
    number: lightboard-2-7
    subtype: led
    type: grb
    label: "Right Sling Lower GI"
  l_behindupperflipper_uppergi_led:
    number: lightboard-8-11
    subtype: led
    type: grb
    label: "Behind Top Right Flipper Upper GI"
  l_behindupperflipper_lowergi_led:
    number: lightboard-8-12
    subtype: led
    type: grb
    label: "Behind Top Right Flipper Lower GI"
  l_behinddropflasher_leftgi_led:
    number: lightboard-4-10
    subtype: led
    type: grb
    label: "Behind Drop Flasher Left GI"
  l_backpanel_gi1_led:
    number: lightboard-7-1
    subtype: led
    type: grb
    label: "Back Panel GI 1"
  l_backpanel_gi2_led:
    number: lightboard-7-2
    subtype: led
    type: grb
    label: "Back Panel GI 2"
  l_backpanel_gi3_led:
    number: lightboard-7-3
    subtype: led
    type: grb
    label: "Back Panel GI 3"
  l_backpanel_gi4_led:
    number: lightboard-7-4
    subtype: led
    type: grb
    label: "Back Panel GI 4"
  l_backpanel_gi5_led:
    number: lightboard-7-5
    subtype: led
    type: grb
    label: "Back Panel GI 5"
  l_stadium_left_1:
    number: lightboard-1-1
    subtype: led
    type: rgb
    label: "Stadium Left 1"
  l_stadium_left_2:
    number: lightboard-1-2
    subtype: led
    type: rgb
    label: "Stadium Left 2"
  l_stadium_left_3:
    number: lightboard-1-3
    subtype: led
    type: rgb
    label: "Stadium Left 3"
  l_stadium_left_4:
    number: lightboard-1-4
    subtype: led
    type: rgb
    label: "Stadium Left 4"
  l_stadium_left_5:
    number: lightboard-1-5
    subtype: led
    type: rgb
    label: "Stadium Left 5"
  l_stadium_left_6:
    number: lightboard-1-6
    subtype: led
    type: rgb
    label: "Stadium Left 6"
  l_stadium_left_7:
    number: lightboard-1-7
    subtype: led
    type: rgb
    label: "Stadium Left 7"
  l_stadium_left_8:
    number: lightboard-1-8
    subtype: led
    type: rgb
    label: "Stadium Left 8"
  l_stadium_left_9:
    number: lightboard-1-9
    subtype: led
    type: rgb
    label: "Stadium Left 9"
  l_stadium_left_10:
    number: lightboard-1-10
    subtype: led
    type: rgb
    label: "Stadium Left 10"
  l_stadium_left_11:
    number: lightboard-1-11
    subtype: led
    type: rgb
    label: "Stadium Left 11"
  l_stadium_left_12:
    number: lightboard-1-12
    subtype: led
    type: rgb
    label: "Stadium Left 12"
  l_stadium_left_13:
    number: lightboard-1-13
    subtype: led
    type: rgb
    label: "Stadium Left 13"
  l_stadium_left_14:
    number: lightboard-1-14
    subtype: led
    type: rgb
    label: "Stadium Left 14"
  l_stadium_left_15:
    number: lightboard-1-15
    subtype: led
    type: rgb
    label: "Stadium Left 15"
  l_stadium_left_16:
    number: lightboard-1-16
    subtype: led
    type: rgb
    label: "Stadium Left 16"
  l_stadium_left_17:
    number: lightboard-1-17
    subtype: led
    type: rgb
    label: "Stadium Left 17"
  l_stadium_left_18:
    number: lightboard-1-18
    subtype: led
    type: rgb
    label: "Stadium Left 18"
  l_stadium_left_19:
    number: lightboard-1-19
    subtype: led
    type: rgb
    label: "Stadium Left 19"
  l_stadium_left_20:
    number: lightboard-1-20
    subtype: led
    type: rgb
    label: "Stadium Left 20"
  l_stadium_left_21:
    number: lightboard-1-21
    subtype: led
    type: rgb
    label: "Stadium Left 21"
  l_stadium_left_22:
    number: lightboard-1-22
    subtype: led
    type: rgb
    label: "Stadium Left 22"
  l_stadium_left_23:
    number: lightboard-1-23
    subtype: led
    type: rgb
    label: "Stadium Left 23"
  l_stadium_left_24:
    number: lightboard-1-24
    subtype: led
    type: rgb
    label: "Stadium Left 24"
  l_stadium_left_25:
    number: lightboard-1-25
    subtype: led
    type: rgb
    label: "Stadium Left 25"
  l_stadium_left_26:
    number: lightboard-1-26
    subtype: led
    type: rgb
    label: "Stadium Left 26"
  l_stadium_left_27:
    number: lightboard-1-27
    subtype: led
    type: rgb
    label: "Stadium Left 27"
  l_stadium_right_1:
    number: lightboard-5-1
    subtype: led
    type: rgb
    label: "Stadium Right 1"
  l_stadium_right_2:
    number: lightboard-5-2
    subtype: led
    type: rgb
    label: "Stadium Right 2"
  l_stadium_right_3:
    number: lightboard-5-3
    subtype: led
    type: rgb
    label: "Stadium Right 3"
  l_stadium_right_4:
    number: lightboard-5-4
    subtype: led
    type: rgb
    label: "Stadium Right 4"
  l_stadium_right_5:
    number: lightboard-5-5
    subtype: led
    type: rgb
    label: "Stadium Right 5"
  l_stadium_right_6:
    number: lightboard-5-6
    subtype: led
    type: rgb
    label: "Stadium Right 6"
  l_stadium_right_7:
    number: lightboard-5-7
    subtype: led
    type: rgb
    label: "Stadium Right 7"
  l_stadium_right_8:
    number: lightboard-5-8
    subtype: led
    type: rgb
    label: "Stadium Right 8"
  l_stadium_right_9:
    number: lightboard-5-9
    subtype: led
    type: rgb
    label: "Stadium Right 9"
  l_stadium_right_10:
    number: lightboard-5-10
    subtype: led
    type: rgb
    label: "Stadium Right 10"
  l_stadium_right_11:
    number: lightboard-5-11
    subtype: led
    type: rgb
    label: "Stadium Right 11"
  l_stadium_right_12:
    number: lightboard-5-12
    subtype: led
    type: rgb
    label: "Stadium Right 12"
  l_stadium_right_13:
    number: lightboard-5-13
    subtype: led
    type: rgb
    label: "Stadium Right 13"
  l_stadium_right_14:
    number: lightboard-5-14
    subtype: led
    type: rgb
    label: "Stadium Right 14"
  l_stadium_right_15:
    number: lightboard-5-15
    subtype: led
    type: rgb
    label: "Stadium Right 15"
  l_stadium_right_16:
    number: lightboard-5-16
    subtype: led
    type: rgb
    label: "Stadium Right 16"
  l_stadium_right_17:
    number: lightboard-5-17
    subtype: led
    type: rgb
    label: "Stadium Right 17"
  l_stadium_right_18:
    number: lightboard-5-18
    subtype: led
    type: rgb
    label: "Stadium Right 18"
  l_stadium_right_19:
    number: lightboard-5-19
    subtype: led
    type: rgb
    label: "Stadium Right 19"
  l_stadium_right_20:
    number: lightboard-5-20
    subtype: led
    type: rgb
    label: "Stadium Right 20"
  l_stadium_right_21:
    number: lightboard-5-21
    subtype: led
    type: rgb
    label: "Stadium Right 21"
  l_stadium_right_22:
    number: lightboard-5-22
    subtype: led
    type: rgb
    label: "Stadium Right 22"
  l_stadium_right_23:
    number: lightboard-5-23
    subtype: led
    type: rgb
    label: "Stadium Right 23"
  l_stadium_right_24:
    number: lightboard-5-24
    subtype: led
    type: rgb
    label: "Stadium Right 24"
  l_stadium_right_25:
    number: lightboard-5-25
    subtype: led
    type: rgb
    label: "Stadium Right 25"
  l_stadium_right_26:
    number: lightboard-5-26
    subtype: led
    type: rgb
    label: "Stadium Right 26"
  l_stadium_right_27:
    number: lightboard-5-27
    subtype: led
    type: rgb
    label: "Stadium Right 27"
  l_left_orbit_x:
    number: lightboard-8-13
    subtype: led
    type: rgb
    label: "Left Orbit X"
  l_left_ramp_x:
    number: lightboard-8-14
    subtype: led
    type: rgb
    label: "Left Ramp X"
  l_inner_loop_x:
    number: lightboard-8-15
    subtype: led
    type: rgb
    label: "Upper Loop X"
  l_scoop_x:
    number: lightboard-8-16
    subtype: led
    type: rgb
    label: "Scoop X"
  l_right_ramp_x:
    number: lightboard-8-17
    subtype: led
    type: rgb
    label: "Right Ramp X"
  l_right_orbit_x:
    number: lightboard-8-18
    subtype: led
    type: rgb
    label: "Right Orbit X"


blinkenlights:
  bl_leftorbit_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_leftorbit_arrow_led
  bl_leftramp_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_leftramp_arrow_led
  bl_innerloop_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_innerloop_arrow_led
  bl_scoop_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_scoop_arrow_led
  bl_rightramp_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_rightramp_arrow_led
  bl_rightorbit_arrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_rightorbit_arrow_led
  bl_captiveball_smallcircle_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_captiveball_smallcircle_led
  bl_lowerrightstandup_circle_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_lowerrightstandup_circle_led
  bl_dropstandup_flasher_led:
    off_when_multiple: false
    color_duration: 500ms
    light: l_dropstandup_flasher_led
  bl_upperpop_smallarrow_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_upperpop_smallarrow_led
  bl_tshirttopcircle_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_tshirttopcircle_led
  bl_tshirtbottomcircle_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_tshirtbottomcircle_led
  bl_ballsave_circle_led:
    off_when_multiple: false
    color_duration: 300ms
    light: l_ballsave_circle_led
  bl_lowerrightpop_inside_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_lowerrightpop_inside_led
  bl_lowerrightpop_inside2_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_lowerrightpop_inside2_led
  bl_upperleftpop_inside_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_upperleftpop_inside_led
  bl_uppercenterpop_inside_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_uppercenterpop_inside_led
  bl_dropbank_rectangle_led:
    off_when_multiple: false
    color_duration: 300ms
    light: l_dropbank_rectangle_led
  bl_left_orbit_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_left_orbit_x
  bl_left_ramp_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_left_ramp_x
  bl_inner_loop_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_inner_loop_x
  bl_scoop_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_scoop_x
  bl_right_ramp_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_right_ramp_x
  bl_right_orbit_x:
    off_when_multiple: false
    color_duration: 300ms
    light: l_right_orbit_x
  bl_scoopmode_circle2_led:
    off_when_multiple: false
    color_duration: 750ms
    light: l_scoopmode_circle2_led


