#config_version=6

#You can use variables to define different states and how they react. Please visit https://docs.missionpinball.org/en/latest/machine_vars/index.html

machine_vars:
 game_just_played:
   initial_value: 0
   persist: false
   value_type: int

variable_player:
  machine_reset_phase_2:
    game_just_played:
      action: set_machine
      int: 0
