#config_version=6

mode:
  start_events: carousel_item_selected{item=="makesomenoise"}
  stop_events: mode_makesomenoise_stop, multiball_makesomenoise_ended
  priority: 5001


counters:
  makesomenoise_spins_counter:
    count_events: spinner_hit
    events_when_complete: makesomenoise_spins_counter_complete
    starting_count: 40
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: False
    disable_on_complete: False
    reset_on_complete: False
    disable_events: mode_makesomenoise_ended
    restart_events: mode_makesomenoise_started, makesomenoise_final_shot_hit
    control_events:
      - event: reset_makesomenoise_spins_counter
        action: jump
        value: 40
  makesomenoise_ramps_counter:
    count_events: left_ramp_hit, right_ramp_hit
    events_when_complete: makesomenoise_ramps_counter_complete
    starting_count: 4
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: False
    disable_on_complete: False
    reset_on_complete: False
    disable_events: mode_makesomenoise_ended
    restart_events: mode_makesomenoise_started, makesomenoise_final_shot_hit
    control_events:
      - event: reset_makesomenoise_ramps_counter
        action: jump
        value: 4
  makesomenoise_drops_counter:
    count_events: drop_target_middle_down, drop_target_bottom_down, drop_target_top_down
    events_when_complete: makesomenoise_drops_counter_complete
    starting_count: 6
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: False
    disable_on_complete: False
    reset_on_complete: False
    disable_events: mode_makesomenoise_ended
    restart_events: mode_makesomenoise_started, makesomenoise_final_shot_hit
    control_events:
      - event: reset_makesomenoise_drops_counter
        action: jump
        value: 6
  makesomenoise_pops_counter:
    count_events: pop1_hit, pop2_hit, pop3_hit
    events_when_complete: makesomenoise_pops_counter_complete
    starting_count: 10
    count_complete_value: 0
    count_interval: 1
    direction: down
    persist_state: False
    disable_on_complete: False
    reset_on_complete: False
    disable_events: mode_makesomenoise_ended
    restart_events: mode_makesomenoise_started, makesomenoise_final_shot_hit
    control_events:
      - event: reset_makesomenoise_pops_counter
        action: jump
        value: 10


accruals:
  completing_makesomenoise_counters:
    events:
      - makesomenoise_pops_counter_complete
      - makesomenoise_ramps_counter_complete
      - makesomenoise_drops_counter_complete
      - makesomenoise_spins_counter_complete
    events_when_complete: makesomenoise_final_shot_lit
    restart_events: mode_makesomenoise_started, makesomenoise_final_shot_hit


sequences:
  makesomenoise_final_shot:
    events:
      - scoop_hit
    enable_events: makesomenoise_final_shot_lit
    events_when_complete: makesomenoise_final_shot_hit
    reset_on_complete: True
    start_enabled: False
    restart_events: makesomenoise_final_shot_lit


variable_player:
  makesomenoise_drops_counter_complete:
    score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
    mode_makesomenoise_score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  makesomenoise_pops_counter_complete:
    score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
    mode_makesomenoise_score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  makesomenoise_ramps_counter_complete:
    score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
    mode_makesomenoise_score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  makesomenoise_spins_counter_complete:
    score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
    mode_makesomenoise_score: 10000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  makesomenoise_final_shot_hit:
    score: 20000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.scoop_multiplier
    mode_makesomenoise_score: 20000000 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.scoop_multiplier
    makesomenoise_pops_remaining:
      int: 10
      action: set
    makesomenoise_spins_remaining:
      int: 40
      action: set
    makesomenoise_drops_remaining:
      int: 6
      action: set
    makesomenoise_ramps_remaining:
      int: 4
      action: set
  timer_makesomenoise_intro_show_tick:
    makesomenoise_intro_show_variable_times_100:
      int: device.timers.makesomenoise_intro_show.ticks * 100
      action: set
  mode_makesomenoise_started:
    mode_blocking_flag:
      int: 1
      action: set
    mode_makesomenoise_score:
      int: 0
      action: set
    modes_played: 1
    modes_completed: 1
    battery_charged_yesorno:
      int: 0
      action:
        set
    makesomenoise_pops_remaining:
      int: 10
      action: set
    makesomenoise_spins_remaining:
      int: 40
      action: set
    makesomenoise_drops_remaining:
      int: 6
      action: set
    makesomenoise_ramps_remaining:
      int: 4
      action: set
  logicblock_makesomenoise_spins_counter_hit:
    makesomenoise_spins_remaining:
      int: -1
      action: add
  logicblock_makesomenoise_pops_counter_hit:
    makesomenoise_pops_remaining:
      int: -1
      action: add
  logicblock_makesomenoise_ramps_counter_hit:
    makesomenoise_ramps_remaining:
      int: -1
      action: add
  logicblock_makesomenoise_drops_counter_hit:
    makesomenoise_drops_remaining:
      int: -1
      action: add
  right_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  left_inlane_hit:
    score: 
      int: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  right_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  left_outlane_hit:
    score: 
      int: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  s_left_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 10 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  s_right_slingshot_active:
    score: 
      int: 10 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 10 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  pop1_hit:
    score: 
      int: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  pop2_hit:
    score: 
      int: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  pop3_hit:
    score: 
      int: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 1110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  upper_pop_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  pop_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  captive_ball_hit:
    score: 
      int: 10010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 10010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  spinner_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
      block: True
    mode_makesomenoise_score: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
  drop_target_bottom_down:
    score: 
      int: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  drop_target_middle_down:
    score: 
      int: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  drop_target_top_down:
    score: 
      int: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 2220 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  scoop_hit:
    score: 
      int: 2310 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.scoop_multiplier
      block: True
    mode_makesomenoise_score: 2310 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.scoop_multiplier
  tshirt_top_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  tshirt_bottom_standup_hit:
    score: 
      int: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 5010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  three_bank_standup_hit:
    score: 
      int: 20010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
      block: True
    mode_makesomenoise_score: 20010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier
  s_left_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
      block: True
    mode_makesomenoise_score: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
  s_right_orbit_active:
    score: 
      int: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_orbit_multiplier
      block: True
    mode_makesomenoise_score: 110 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_orbit_multiplier
  s_inner_orbit_active:
    score: 
      int: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.upper_loop_multiplier
      block: True
    mode_makesomenoise_score: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.upper_loop_multiplier
  left_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_ramp_multiplier
      block: True
    mode_makesomenoise_score: 3010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_ramp_multiplier
  right_ramp_hit:
    score: 
      int: 3010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_ramp_multiplier
      block: True
    mode_makesomenoise_score: 3010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_ramp_multiplier
  left_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
      block: True
    mode_makesomenoise_score: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.left_orbit_multiplier
  right_orbit_hit:
    score: 
      int: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_orbit_multiplier
      block: True
    mode_makesomenoise_score: 1010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.right_orbit_multiplier
  inner_loop_hit:
    score: 
      int: 2010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.upper_loop_multiplier
      block: True
    mode_makesomenoise_score: 2010 * current_player.playfield_x * current_player.makesomenoise_mode_multiplier * current_player.upper_loop_multiplier



slide_player:
  mode_makesomenoise_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    basevideo5:
      action: remove
    basevideo6:
      action: remove
    current_wizard_mode_highlighted:
      action: remove
    makesomenoise:
      action: play
      priority: 500000
    makesomenoise_instructions:
      action: play
      priority: 500001
      expire: 8s
  flipper_cancel{device.ball_holds.wizard_scoop_hold.balls_held==1}:
    makesomenoise_instructions:
      action: remove
  timer_makesomenoise_intro_show_complete:
    makesomenoise_drops_counter:
      action: play
      priority: 800000
    makesomenoise_pops_counter:
      action: play
      priority: 800000
    makesomenoise_spins_counter:
      action: play
      priority: 800000
    makesomenoise_ramps_counter:
      action: play
      priority: 800000
  makesomenoise_final_shot_lit:
    makesomenoise_final_shot_lit:
      action: play
      priority: 800000
    makesomenoise_spins_counter:
      action: remove
    makesomenoise_ramps_counter:
      action: remove
    makesomenoise_drops_counter:
      action: remove
    makesomenoise_pops_counter:
      action: remove
  makesomenoise_final_shot_hit:
    makesomenoise_final_shot_lit:
      action: remove
    makesomenoise_superjackpot:
      action: play
      expire: 3s
      priority: 800000
  slide_makesomenoise_superjackpot_removed:
    makesomenoise_drops_counter:
      action: play
      priority: 800000
    makesomenoise_pops_counter:
      action: play
      priority: 800000
    makesomenoise_spins_counter:
      action: play
      priority: 800000
    makesomenoise_ramps_counter:
      action: play
      priority: 800000
  makesomenoise_drops_counter_complete:
    makesomenoise_drops_counter:
      action: remove
  makesomenoise_spins_counter_complete:
    makesomenoise_spins_counter:
      action: remove
  makesomenoise_pops_counter_complete:
    makesomenoise_pops_counter:
      action: remove
  makesomenoise_ramps_counter_complete:
    makesomenoise_ramps_counter:
      action: remove


sound_player:
  mode_makesomenoise_started:
    makesomenoisemusic:
      action: replace
      bus: music
      loops: 5
  makesomenoise_drops_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  makesomenoise_pops_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  makesomenoise_ramps_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  makesomenoise_spins_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  makesomenoise_final_shot_hit:
    success_finish:
      action: play
      bus: effects
      max_queue_time: 1s



timers:
  makesomenoise_intro_show:
    start_value: 0
    end_value: 10
    control_events:
      - action: start
        event: mode_makesomenoise_started
      - action: jump
        value: 10
        event: flipper_cancel{device.ball_holds.wizard_scoop_hold.balls_held==1}


show_player:
  mode_makesomenoise_started:
    makesomenoise_stadium_intro_lights:
      action: play
      loops: -1
  timer_makesomenoise_intro_show_complete:
    makesomenoise_stadium_intro_lights:
      action: stop
    makesomenoise_backboard_show:
      action: play
      loops: -1
    makesomenoise_ramps_shot:
      action: play
      loops: -1
    makesomenoise_spins_shot:
      action: play
      loops: -1
    makesomenoise_pops_shot:
      action: play
      loops: -1
    makesomenoise_drops_shot:
      action: play
      loops: -1
    ball_save_show:
      action: play
      loops: -1
  makesomenoise_ramps_counter_complete:
    makesomenoise_ramps_shot:
      action: stop
  makesomenoise_spins_counter_complete:
    makesomenoise_spins_shot:
      action: stop
  makesomenoise_pops_counter_complete:
    makesomenoise_pops_shot:
      action: stop
  makesomenoise_drops_counter_complete:
    makesomenoise_drops_shot:
      action: stop
  makesomenoise_final_shot_lit:
    makesomenoise_final_shot:
      action: play
      loops: -1
  makesomenoise_final_shot_hit:
    makesomenoise_final_shot:
      action: stop
    makesomenoise_ramps_shot:
      action: play
      loops: -1
    makesomenoise_spins_shot:
      action: play
      loops: -1
    makesomenoise_pops_shot:
      action: play
      loops: -1
    makesomenoise_drops_shot:
      action: play
      loops: -1
  multiball_makesomenoise_shoot_again_ended:
    ball_save_show:
      action: stop


shot_profiles:
  makesomenoise_shot:
    advance_on_hit: False
    states:
      - name: "off"
      - name: lit
        show: flash_color
        show_tokens:
          color: DodgerBlue
        speed: 2
    loop: False

