#config_version=6

mode:
  start_events: carousel_item_selected{item=="bodhisattvavow"}
  stop_events: mode_bodhivow_stop, timer_bodhisattvavow_time_remaining_complete
  priority: 5001


counters:
  bodhisattvavow_area1_counter:
    count_events: inner_loop_hit, captive_ball_hit, scoop_hit, upper_pop_standup_hit, tshirt_top_standup_hit, tshirt_bottom_standup_hit
    events_when_complete: bodhisattvavow_area1_counter_complete
    starting_count: 1
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: False
    disable_on_complete: False
    reset_on_complete: True
    disable_events: mode_bodhivow_ended
    restart_events: mode_bodhivow_started, bodhisattvavow_area1_counter_complete
  bodhisattvavow_area2_counter:
    count_events: left_orbit_hit, left_ramp_hit
    events_when_complete: bodhisattvavow_area2_counter_complete
    starting_count: 1
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: False
    disable_on_complete: False
    reset_on_complete: True
    disable_events: mode_bodhivow_ended
    restart_events: mode_bodhivow_started, bodhisattvavow_area2_counter_complete
  bodhisattvavow_area3_counter:
    count_events: right_ramp_hit, right_orbit_hit
    events_when_complete: bodhisattvavow_area3_counter_complete
    starting_count: 1
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: False
    disable_on_complete: False
    reset_on_complete: True
    disable_events: mode_bodhivow_ended
    restart_events: mode_bodhivow_started, bodhisattvavow_area3_counter_complete
  bodhisattvavow_area4_counter:
    count_events: left_outlane_hit, three_bank_standup_hit, drop_target_bank_three_bank_down
    events_when_complete: bodhisattvavow_area4_counter_complete
    starting_count: 1
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: False
    disable_on_complete: False
    reset_on_complete: True
    disable_events: mode_bodhivow_ended
    restart_events: mode_bodhivow_started, bodhisattvavow_area4_counter_complete
  bodhisattvavow_area5_counter:
    count_events: pop3_hit, pop_standup_hit, right_outlane_hit
    events_when_complete: bodhisattvavow_area5_counter_complete
    starting_count: 1
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: False
    disable_on_complete: False
    reset_on_complete: True
    disable_events: mode_bodhivow_ended
    restart_events: mode_bodhivow_started, bodhisattvavow_area5_counter_complete


variable_player:
  timer_bodhisattvavow_intro_show_tick:
    bodhisattvavow_intro_show_variable_times_100:
      int: device.timers.bodhisattvavow_intro_show.ticks * 100
      action: set
  timer_bodhisattvavow_time_remaining_tick:
    bodhisattvavow_time_remaining_variable_times_1:
      int: device.timers.bodhisattvavow_time_remaining.ticks * 1
      action: set
  mode_bodhivow_started:
    mode_blocking_flag:
      int: 1
      action: set
    mode_bodhisattvavow_score:
      int: 0
      action: set
    modes_played: 1
    modes_completed: 1
    battery_charged_yesorno:
      int: 0
      action: set
  counter_bodhisattvavow_area1_counter_hit:
    score: 60000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area1_counter
    mode_bodhisattvavow_score: 5000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area1_counter
    bodhisattvavow_area1_counter:
      int: device.counters.bodhisattvavow_area1_counter.value * 1
      action: set
  bodhisattvavow_area1_counter_complete:
    bodhisattvavow_area1_counter:
      int: 1
      action: set
  counter_bodhisattvavow_area2_counter_hit:
    score: 60000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area2_counter
    mode_bodhisattvavow_score: 5000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area2_counter
    bodhisattvavow_area2_counter:
      int: device.counters.bodhisattvavow_area2_counter.value * 1
      action: set
  bodhisattvavow_area2_counter_complete:
    bodhisattvavow_area2_counter:
      int: 1
      action: set
  counter_bodhisattvavow_area3_counter_hit:
    score: 60000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area3_counter
    mode_bodhisattvavow_score: 5000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area3_counter
    bodhisattvavow_area3_counter:
      int: device.counters.bodhisattvavow_area3_counter.value * 1
      action: set
  bodhisattvavow_area3_counter_complete:
    bodhisattvavow_area3_counter:
      int: 1
      action: set
  counter_bodhisattvavow_area4_counter_hit:
    score: 60000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area4_counter
    mode_bodhisattvavow_score: 5000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area4_counter
    bodhisattvavow_area4_counter:
      int: device.counters.bodhisattvavow_area4_counter.value * 1
      action: set
  bodhisattvavow_area4_counter_complete:
    bodhisattvavow_area4_counter:
      int: 1
      action: set
  counter_bodhisattvavow_area5_counter_hit:
    score: 60000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area5_counter
    mode_bodhisattvavow_score: 5000 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier * current_player.bodhisattvavow_area5_counter
    bodhisattvavow_area5_counter:
      int: device.counters.bodhisattvavow_area5_counter.value * 1
      action: set
  bodhisattvavow_area5_counter_complete:
    bodhisattvavow_area5_counter:
      int: 1
      action: set
  right_inlane_hit:
    score:
      int: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  left_inlane_hit:
    score:
      int: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  s_left_slingshot_active:
    score:
      int: 10 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 10 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  s_right_slingshot_active:
    score:
      int: 10 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 10 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  pop1_hit:
    score:
      int: 1110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 1110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  pop2_hit:
    score:
      int: 1110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 1110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  spinner_hit:
    score:
      int: 1010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 1010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  bottom_drop_hit:
    score:
      int: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  middle_drop_hit:
    score:
      int: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  top_drop_hit:
    score:
      int: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 2220 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  three_bank_standup_hit:
    score:
      int: 20010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 20010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  s_left_orbit_active:
    score:
      int: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  s_right_orbit_active:
    score:
      int: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 110 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
  s_inner_orbit_active:
    score:
      int: 1010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier
      block: True
    mode_bodhisattvavow_score: 1010 * current_player.playfield_x * current_player.bodhisattvavow_mode_multiplier


event_player:
  bodhisattvavow_area1_counter_complete: add_bodhisattvavow_time_3s
  bodhisattvavow_area2_counter_complete: add_bodhisattvavow_time_3s
  bodhisattvavow_area3_counter_complete: add_bodhisattvavow_time_3s
  bodhisattvavow_area4_counter_complete: add_bodhisattvavow_time_3s
  bodhisattvavow_area5_counter_complete: add_bodhisattvavow_time_3s


slide_player:
  mode_bodhivow_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    current_wizard_mode_highlighted:
      action: remove
    bodhisattvavow:
      action: play
      priority: 500000
    bodhisattvavow_instructions:
      action: play
      priority: 500001
      expire: 8s
  timer_bodhisattvavow_intro_show_complete:
    bodhisattvavow_instructions:
      action: remove
    bodhisattvavow_display_timer:
      action: play
      priority: 1000000


sound_player:
  mode_bodhivow_started:
    bodhisattvavowmusic:
      action: replace
      bus: music
      loops: 5
  bodhisattvavow_area1_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  bodhisattvavow_area2_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  bodhisattvavow_area3_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  bodhisattvavow_area4_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  bodhisattvavow_area5_counter_complete:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms


timers:
  bodhisattvavow_intro_show:
    start_value: 0
    end_value: 8
    control_events:
      - action: start
        event: mode_bodhivow_started
      - action: jump
        value: 8
        event: flipper_cancel{device.ball_holds.wizard_scoop_hold.balls_held==1}
  bodhisattvavow_time_remaining:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_bodhisattvavow_intro_show_complete
      - action: pause
        event: multiball_bodhisattvavow_ended
      - action: add
        value: 3
        event: add_bodhisattvavow_time_3s


show_player:
  mode_bodhivow_started:
    left_orbit_mult_show:
      action: stop
    left_ramp_mult_show:
      action: stop
    upper_loop_mult_show:
      action: stop
    scoop_mult_show:
      action: stop
    right_ramp_mult_show:
      action: stop
    right_orbit_mult_show:
      action: stop
  ball_hold_wizard_scoop_hold_balls_released:
    ball_save_show:
      action: play
      loops: -1
    bodhisattvavow_area1_green:
      action: play
      loops: -1
      priority: 500000
    bodhisattvavow_area2_green:
      action: play
      loops: -1
      priority: 500000
    bodhisattvavow_area3_green:
      action: play
      loops: -1
      priority: 500000
    bodhisattvavow_area4_green:
      action: play
      loops: -1
      priority: 500000
    bodhisattvavow_area5_green:
      action: play
      loops: -1
      priority: 500000
  multiball_bodhisattvavow_shoot_again_ended:
    ball_save_show:
      action: stop
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter!=1}:
    bodhisattvavow_area1_green:
      action: stop
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter==2}:
    bodhisattvavow_area1_purple:
      action: stop
    bodhisattvavow_area1_yellow:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter!=2}:
    bodhisattvavow_area1_yellow:
      action: stop
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter==3}:
    bodhisattvavow_area1_blue:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter!=3}:
    bodhisattvavow_area1_blue:
      action: stop
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter==4}:
    bodhisattvavow_area1_red:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area1_counter{current_player.bodhisattvavow_area1_counter!=4}:
    bodhisattvavow_area1_red:
      action: stop
  bodhisattvavow_area1_counter_complete:
    bodhisattvavow_area1_purple:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter!=1}:
    bodhisattvavow_area2_green:
      action: stop
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter==2}:
    bodhisattvavow_area2_purple:
      action: stop
    bodhisattvavow_area2_yellow:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter!=2}:
    bodhisattvavow_area2_yellow:
      action: stop
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter==3}:
    bodhisattvavow_area2_blue:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter!=3}:
    bodhisattvavow_area2_blue:
      action: stop
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter==4}:
    bodhisattvavow_area2_red:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area2_counter{current_player.bodhisattvavow_area2_counter!=4}:
    bodhisattvavow_area2_red:
      action: stop
  bodhisattvavow_area2_counter_complete:
    bodhisattvavow_area2_purple:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter!=1}:
    bodhisattvavow_area3_green:
      action: stop
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter==2}:
    bodhisattvavow_area3_purple:
      action: stop
    bodhisattvavow_area3_yellow:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter!=2}:
    bodhisattvavow_area3_yellow:
      action: stop
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter==3}:
    bodhisattvavow_area3_blue:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter!=3}:
    bodhisattvavow_area3_blue:
      action: stop
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter==4}:
    bodhisattvavow_area3_red:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area3_counter{current_player.bodhisattvavow_area3_counter!=4}:
    bodhisattvavow_area3_red:
      action: stop
  bodhisattvavow_area3_counter_complete:
    bodhisattvavow_area3_purple:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter!=1}:
    bodhisattvavow_area4_green:
      action: stop
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter==2}:
    bodhisattvavow_area4_purple:
      action: stop
    bodhisattvavow_area4_yellow:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter!=2}:
    bodhisattvavow_area4_yellow:
      action: stop
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter==3}:
    bodhisattvavow_area4_blue:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter!=3}:
    bodhisattvavow_area4_blue:
      action: stop
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter==4}:
    bodhisattvavow_area4_red:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area4_counter{current_player.bodhisattvavow_area4_counter!=4}:
    bodhisattvavow_area4_red:
      action: stop
  bodhisattvavow_area4_counter_complete:
    bodhisattvavow_area4_purple:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter!=1}:
    bodhisattvavow_area5_green:
      action: stop
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter==2}:
    bodhisattvavow_area5_purple:
      action: stop
    bodhisattvavow_area5_yellow:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter!=2}:
    bodhisattvavow_area5_yellow:
      action: stop
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter==3}:
    bodhisattvavow_area5_blue:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter!=3}:
    bodhisattvavow_area5_blue:
      action: stop
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter==4}:
    bodhisattvavow_area5_red:
      action: play
      loops: -1
      priority: 500000
  player_bodhisattvavow_area5_counter{current_player.bodhisattvavow_area5_counter!=4}:
    bodhisattvavow_area5_red:
      action: stop
  bodhisattvavow_area5_counter_complete:
    bodhisattvavow_area5_purple:
      action: play
      loops: -1
      priority: 500000


ball_saves:
  fake_bodhisattvavow_ball_save:
    enable_events: timer_bodhisattvavow_time_remaining_complete
    auto_launch: false
    balls_to_save: 1
    debug: true



blinkenlight_player:
  mode_bodhivow_started:
    bl_left_orbit_x: remove
    bl_left_ramp_x: remove
    bl_inner_loop_x: remove
    bl_scoop_x: remove
    bl_right_ramp_x: remove
    bl_right_orbit_x: remove
