#config_version=6

mode:
  start_events: start_superdrops
  stop_events: mode_superdrops_complete
  priority: 20000

variable_player:
  top_drop_hit:
    score: 100000 * current_player.playfield_x
  middle_drop_hit:
    score: 100000 * current_player.playfield_x
  bottom_drop_hit:
    score: 100000 * current_player.playfield_x

timers:
  superdrops_timer:
    start_value: 0
    end_value: 30
    tick_interval: 1s
    start_running: True
    control_events:
      - event: mode_superdrops_started
        action: restart
      - event: ball_ending
        action: stop

event_player:
  timer_superdrops_timer_complete: mode_superdrops_complete


random_event_player:
  mode_superdrops_started:
    events:
      - adrock1_sound
      - adrock2_sound
      - adrock3_sound
      - adrock4_sound
      - adrock5_sound
      - adrock6_sound
      - adrock7_sound
      - adrock8_sound
      - adrockrobot_sound
      - adrockadam_sound
      - adrockadam2_sound


sound_player:
  adrock1_sound:
    name_adrock_1:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock2_sound:
    name_adrock_2:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock3_sound:
    name_adrock_3:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock4_sound:
    name_adrock_4:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock5_sound:
    name_adrock_5:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock6_sound:
    name_adrock_6:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock7_sound:
    name_adrock_7:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrock8_sound:
    name_adrock_8:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrockrobot_sound:
    name_adrock_robot:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrockadam_sound:
    name_adrock_adam1:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
  adrockadam2_sound:
    name_adrock_adam2:
      action: load
      bus: voice
    superdrops_callout:
      action: load
      bus: voice
