#config_version=6

mode:
  code: mpf.modes.tilt.code.tilt.Tilt
  priority: 1000000
  start_events: game_started #machine_reset_phase_3
  game_mode: False
  stop_on_ball_end: False

# Instructions on how to use this mode:
# https://missionpinball.org/game_logic/tilt


#timers:
#  upper_flipper_tilt:
#    start_running: False
#    restart_on_complete: True
#    start_value: 0
#    end_value: 10
#    tick_interval: 10s
#    control_events:
#      - event: tilt
#        action: restart
#      - event: ball_will_start
#        action: stop


#event_player:
#  timer_upper_flipper_tilt_complete: s_top_right_flipper


tilt:
  tilt_warning_switch_tag: tilt_warning
  tilt_switch_tag: tilt
  slam_tilt_switch_tag: slam_tilt
  tilt_warnings_player_var: tilt_warnings
  multiple_hit_window: settings.multiple_hit_window
  settle_time: settings.settle_time
  warnings_to_tilt: settings.warnings_to_tilt
  reset_warnings_events: ball_will_end, ball_started


slide_player:
  tilt_warning_1:
    tilt_warning_1:
      action: play
      priority: 1000000
      expire: 2s
  tilt_warning_2:
    tilt_warning_1:
      action: remove
    tilt_warning_2:
      action: play
      priority: 1000000
      expire: 2s
  tilt:
    tilt_warning_2:
      action: remove
  tilt1:
    tilt1:
      action: play
      priority: 1000000
      expire: 8s
  tilt2:
    tilt2:
      action: play
      priority: 1000000
      expire: 7s
  tilt3:
    tilt3:
      action: play
      priority: 1000000
      expire: 7s
  tilt4:
    tilt4:
      action: play
      priority: 1000000
      expire: 22s
  tilt5:
    tilt5:
      action: play
      priority: 1000000
      expire: 10s
  tilt6:
    tilt6:
      action: play
      priority: 1000000
      expire: 11s
  tilt_clear:
    tilt1:
      action: remove
    tilt2:
      action: remove
    tilt3:
      action: remove
    tilt4:
      action: remove
    tilt5:
      action: remove
    tilt6:
      action: remove


sound_player:
  tilt_warning_1:
    tilt_warning_sound_random:
      action: play
      bus: effects
  tilt_warning_2:
    tilt_warning_sound_random:
      action: play
      bus: effects
