#config_version=6

mode:
  start_events: start_girls
  stop_events: mode_girls_complete
  priority: 5000


timers:
  girls_intro_show:
    start_value: 0
    end_value: 8
    control_events:
      - action: start
        event: mode_girls_started
  girls_time_remaining:
    start_value: 30
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_girls_intro_show_complete
      - action: reset
        event: mode_girls_started


slide_player:
  mode_girls_started:
    current_mode_highlighted:
      action: remove
    girls_instructions:
      action: play
      priority: 825000
  timer_girls_intro_show_complete:
    girls_instructions:
      action: remove
    girls_display_timer:
      action: play
      priority: 830000


variable_player:
  mode_girls_started:
    girls_blocking_flag:
      int: 1
      action: set
  pop1_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  pop2_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  pop3_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  top_drop_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  middle_drop_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  bottom_drop_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  left_outlane_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  left_inlane_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  right_inlane_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  right_outlane_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  s_left_slingshot_active:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  s_right_slingshot_active:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  upper_pop_standup_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  pop_standup_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  captive_ball_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  spinner_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  scoop_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  tshirt_top_standup_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  tshirt_bottom_standup_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  s_left_orbit_active:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  s_right_orbit_active:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  s_inner_orbit_active:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  left_ramp_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  right_ramp_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x
  three_bank_standup_hit:
    score: 3000 * current_player.playfield_x
    girls_bonus_score: 3000 * current_player.playfield_x


sound_player:
  mode_girls_started:
    girlsinstrumentalmusic:
      action: replace
      bus: music
  pop1_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop2_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop3_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  top_drop_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  middle_drop_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  bottom_drop_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_outlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_inlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_inlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_outlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_left_slingshot_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_right_slingshot_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  upper_pop_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  captive_ball_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  spinner_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  scoop_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  tshirt_top_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  tshirt_bottom_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_left_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_right_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_inner_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_ramp_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_ramp_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  three_bank_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db

event_player:
  timer_girls_time_remaining_complete: mode_girls_complete