#config_version=6

mode:
  start_events: start_girls
  stop_events: mode_girls_complete
  priority: 5000


timers:
  girls_intro_show:
    start_value: 0
    end_value: 8
    control_events:
      - action: start
        event: mode_girls_started
  girls_time_remaining:
    start_value: 30
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_girls_intro_show_complete
      - action: reset
        event: mode_girls_started


slide_player:
  mode_girls_started:
    current_mode_highlighted:
      action: remove
    girls_instructions:
      action: play
      priority: 825000
  timer_girls_intro_show_complete:
    girls_instructions:
      action: remove
    girls_display_timer:
      action: play
      priority: 830000


variable_player:
  mode_girls_started:
    girls_blocking_flag:
      int: 1
      action: set
  pop1_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  pop2_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  pop3_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  drop_target_top_down:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  drop_target_middle_down:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  drop_target_bottom_down:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  left_outlane_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  left_inlane_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  right_inlane_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  right_outlane_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  s_left_slingshot_active:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  s_right_slingshot_active:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  upper_pop_standup_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  pop_standup_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  captive_ball_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  spinner_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  scoop_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.scoop_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.scoop_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  machine_var_audits_s_tshirt_top_standup:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  machine_var_audits_s_tshirt_bottom_standup:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  s_left_orbit_active:
    score:
      int: 750000 * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.left_orbit_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  s_right_orbit_active:
    score:
      int: 750000 * current_player.playfield_x * current_player.right_orbit_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.right_orbit_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  s_inner_orbit_active:
    score:
      int: 750000 * current_player.playfield_x * current_player.upper_loop_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.upper_loop_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  left_ramp_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.left_ramp_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.left_ramp_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  right_ramp_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.right_ramp_multiplier * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.right_ramp_multiplier * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  three_bank_standup_hit:
    score:
      int: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
      block: True
    girls_frenzy_score: 750000 * current_player.playfield_x * current_player.loop_shot_multiplier
    girls_bonus_score: 5000
  timer_girls_time_remaining_tick:
    girls_time_remaining_variable_times_1:
      int: device.timers.girls_time_remaining.ticks * 1
      action: set


sound_player:
  mode_girls_started:
    girlsinstrumentalmusic:
      action: replace
      bus: music
  pop1_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop2_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop3_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  drop_target_top_down:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  drop_target_middle_down:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  drop_target_bottom_down:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_outlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_inlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_inlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_outlane_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_left_slingshot_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_right_slingshot_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  upper_pop_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  pop_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  captive_ball_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  spinner_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  scoop_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  machine_var_audits_s_tshirt_top_standup:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  machine_var_audits_s_tshirt_bottom_standup:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_left_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_right_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  s_inner_orbit_active:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  left_ramp_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  right_ramp_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db
  three_bank_standup_hit:
    girlsvocal:
      action: play
      bus: effects
      max_queue_time: 100ms
      volume: 1.2 db

event_player:
  timer_girls_time_remaining_complete: mode_girls_complete