#config_version=6


mode_settings:
  non_match_number_step: 10


queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: match_video_done
    pass_args: True
  match_has_match:
    post: has_match
    wait_for: match_video_done
    pass_args: True



slide_player:
  mode_match_started:
    bonus_total_slide:
      action: remove
    high_score_award_display:
      action: remove
  no_match:
    no_match_slide:
      expire: 14s
  has_match:
    match_slide:
      expire: 14s
  match_video_done:
    no_match_slide_1:
      action: remove
    match_slide_1:
      action: remove


sound_player:
  no_match:
    futurama_match_audio:
      action: replace
      bus: music
  has_match:
    futurama_match_audio:
      action: replace
      bus: music

