#config_version=6


mode_settings:
  non_match_number_step: 10


queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: match_video_done
    pass_args: True
  match_has_match:
    post: has_match
    wait_for: match_video_done
    pass_args: True



slide_player:
  mode_match_started:
    bonus_total_slide:
      action: remove
    high_score_award_display:
      action: remove
  no_match{machine.this_game_match_video==1}:
    no_match_normal_slide:
      action: play
  has_match{machine.this_game_match_video==1}:
    match_normal_slide:
      action: play
  no_match{machine.this_game_match_video==2}:
    no_match_mahjong_slide:
      action: play
  has_match{machine.this_game_match_video==2}:
    match_mahjong_slide:
      action: play
  no_match{machine.this_game_match_video==3}:
    no_match_mother_slide:
      action: play
  has_match{machine.this_game_match_video==3}:
    match_mother_slide:
      action: play
  no_match{machine.this_game_match_video==4}:
    no_match_grammy_slide:
      action: play
  has_match{machine.this_game_match_video==4}:
    match_grammy_slide:
      action: play
  match_video_done:
    match_normal_slide:
      action: remove
    match_mahjong_slide:
      action: remove
    match_mother_slide:
      action: remove
    match_grammy_slide:
      action: remove
    no_match_normal_slide:
      action: remove
    no_match_mahjong_slide:
      action: remove
    no_match_mother_slide:
      action: remove
    no_match_grammy_slide:
      action: remove


sound_player:
  has_match{machine.this_game_match_video==1}:
    futurama_match_audio:
      action: replace
      bus: music
  has_match{machine.this_game_match_video==3}:
    mother_match_audio:
      action: replace
      bus: music
  has_match{machine.this_game_match_video==2}:
    mahjong_match_audio:
      action: replace
      bus: music
  has_match{machine.this_game_match_video==4}:
    grammy_match_audio:
      action: replace
      bus: music
  no_match{machine.this_game_match_video==1}:
    futurama_match_audio:
      action: replace
      bus: music
  no_match{machine.this_game_match_video==3}:
    mother_match_audio:
      action: replace
      bus: music
  no_match{machine.this_game_match_video==2}:
    mahjong_match_audio:
      action: replace
      bus: music
  no_match{machine.this_game_match_video==4}:
    grammy_match_audio:
      action: replace
      bus: music

event_player:
  flipper_cancel: match_video_done
  sw_start_inactive: match_video_done
