#config_version=6

mode:
  start_events: carousel_intergalactic_selected
  stop_events: mode_intergalactic_stop, mode_intergalactic_failed, mode_intergalactic_success, ball_will_end
  priority: 1000

sequences:
  intergalactic_shot_1:
    events:
      - right_ramp_hit, right_orbit_hit
    events_when_complete: intergalactic_shot_1_done
    reset_on_complete: False
  intergalactic_shot_2:
    events:
      - left_ramp_hit, left_orbit_hit
    enable_events: intergalactic_shot_1_done
    events_when_complete: intergalactic_shot_2_done
    reset_on_complete: False
  intergalactic_shot_3:
    events:
      - right_ramp_hit, right_orbit_hit
    enable_events: intergalactic_shot_2_done
    events_when_complete: intergalactic_shot_3_done
    reset_on_complete: False
  intergalactic_shot_4:
    events:
      - left_ramp_hit, left_orbit_hit
    enable_events: intergalactic_shot_3_done
    events_when_complete: intergalactic_shot_4_done
    reset_on_complete: False
  intergalactic_shot_5:
    events:
      - pop_standup_hit
    enable_events: intergalactic_shot_4_done
    events_when_complete: intergalactic_shot_5_done, mode_intergalactic_stop
    reset_on_complete: False


variable_player:
  intergalactic_shot_1_done:
    score: 1000000
    mode_intergalactic_score: 1000000
  intergalactic_shot_2_done:
    score: 2000000
    mode_intergalactic_score: 2000000
  intergalactic_shot_3_done:
    score: 3000000
    mode_intergalactic_score: 3000000
  intergalactic_shot_4_done:
    score: 5000000
    mode_intergalactic_score: 5000000
  intergalactic_shot_5_done:
    score: 10000000
    mode_intergalactic_score: 10000000
  timer_intergalactic_intro_show_tick:
    intergalactic_intro_show_variable_times_100:
      int: device.timers.intergalactic_intro_show.ticks * 100
      action: set
  timer_intergalactic_time_remaining_tick:
    intergalactic_time_remaining_variable_times_1:
      int: device.timers.intergalactic_time_remaining.ticks * 1
      action: set
  mode_intergalactic_started:
    mode_blocking_flag:
      int: 1
      action: set

slide_player:
  mode_intergalactic_started:
    current_mode_highlighted:
      action: remove
    base:
      action: remove
    basevideo1:
      action: remove
    basevideo2:
      action: remove
    basevideo3:
      action: remove
    basevideo4:
      action: remove
    intergalactic:
      action: play
      priority: 500000
    intergalactic_instructions:
      action: play
      priority: 500001
      expire: 9s
  flipper_cancel:
    intergalactic_instructions:
      action: remove
  timer_intergalactic_intro_show_complete:
    intergalactic_right_shot_lit:
      action: play
      priority: 800000
    intergalactic_display_timer:
      action: play
      priority: 825000
  intergalactic_shot_1_done:
    intergalactic_right_shot_lit:
      action: remove
    intergalactic_left_shot_lit:
      action: play
      priority: 800000
  intergalactic_shot_2_done:
    intergalactic_left_shot_lit:
      action: remove
    intergalactic_right_shot_lit:
      action: play
      priority: 800000
  intergalactic_shot_3_done:
    intergalactic_right_shot_lit:
      action: remove
    intergalactic_left_shot_lit:
      action: play
      priority: 800000
  intergalactic_shot_4_done:
    intergalactic_left_shot_lit:
      action: remove
    intergalactic_final_shot_lit:
      action: play
      priority: 800000
  intergalactic_shot_5_done:
    intergalactic_final_shot_lit:
      action: remove
    intergalactic_display_timer:
      action: remove
  timer_intergalactic_time_remaining_complete:
    intergalactic_display_timer:
      action: remove


sound_player:
  mode_intergalactic_started:
    intergalacticmusic:
      action: play
      bus: music
  intergalactic_shot_1_done:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  intergalactic_shot_2_done:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  intergalactic_shot_3_done:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  intergalactic_shot_4_done:
    success_shot:
      action: play
      bus: effects
      max_queue_time: 500ms
  intergalactic_shot_5_done:
    success_finish:
      action: play
      bus: effects
      max_queue_time: 1s


ball_holds:
  intergalactic_scoop_hold:
    balls_to_hold: 1
    hold_devices: bd_scoop
    enable_events: mode_intergalactic_started
    disable_events: timer_intergalactic_intro_show_complete
    release_one_events: timer_intergalactic_intro_show_complete

timers:
  intergalactic_intro_show:
    start_value: 0
    end_value: 13
    control_events:
      - action: start
        event: mode_intergalactic_started
      - action: jump
        value: 13
        event: flipper_cancel{device.ball_holds.intergalactic_scoop_hold.balls_held==1}
  intergalactic_time_remaining:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: timer_intergalactic_intro_show_complete
      - action: pause
        event: intergalactic_shot_5_done
      - action: reset
        event: mode_intergalactic_started
      - action: add
        value: 5
        event: add_intergalactic_time_5s
      - action: add
        value: 15
        event: add_intergalactic_time_15s

event_player:
  timer_intergalactic_time_remaining_complete: mode_intergalactic_failed
  intergalactic_shot_5_done: mode_intergalactic_success
  pop_standup_hit: add_intergalactic_time_15s
  intergalactic_shot_1_done: add_intergalactic_time_5s
  intergalactic_shot_2_done: add_intergalactic_time_5s
  intergalactic_shot_3_done: add_intergalactic_time_5s
  intergalactic_shot_4_done: add_intergalactic_time_5s


show_player:
  intergalactic_shot_4_done:
    intergalactic_final_shot:
      action: play
      loops: -1

blinkenlight_player:
  timer_intergalactic_intro_show_complete:
    bl_rightorbit_arrow_led:
      color: yellow
    bl_rightramp_arrow_led:
      color: yellow
  intergalactic_shot_1_done:
    bl_rightorbit_arrow_led: remove
    bl_rightramp_arrow_led: remove
    bl_leftorbit_arrow_led:
      color: yellow
    bl_leftramp_arrow_led:
      color: yellow
  intergalactic_shot_2_done:
    bl_leftorbit_arrow_led: remove
    bl_leftramp_arrow_led: remove
    bl_rightorbit_arrow_led:
      color: yellow
    bl_rightramp_arrow_led:
      color: yellow
  intergalactic_shot_3_done:
    bl_rightorbit_arrow_led: remove
    bl_rightramp_arrow_led: remove
    bl_leftorbit_arrow_led:
      color: yellow
    bl_leftramp_arrow_led:
      color: yellow
  intergalactic_shot_4_done:
    bl_leftorbit_arrow_led: remove
    bl_leftramp_arrow_led: remove


shot_profiles:
  intergalactic_shot:
    advance_on_hit: false
    states:
      - name: "off"
        show: "off"
      - name: lit
        show: flash_color
        show_tokens:
          color: DodgerBlue
        speed: 2
    loop: false

