#config_version=6

mode:
  start_events: start_superspins
  stop_events: mode_superspins_complete
  priority: 20000

variable_player:
  spinner_hit:
    score: 100000 * current_player.playfield_x * current_player.left_orbit_multiplier

timers:
  superspins_timer:
    start_value: 0
    end_value: 30
    tick_interval: 1s
    start_running: True
    control_events:
      - event: mode_superspins_started
        action: restart
      - event: ball_ending
        action: stop

event_player:
  timer_superspins_timer_complete: mode_superspins_complete


random_event_player:
  mode_superspins_started:
    events:
      - miked1_sound
      - miked2_sound
      - miked3_sound
      - miked4_sound
      - miked5_sound
      - miked6_sound
      - miked7_sound
      - miked8_sound
      - miked9_sound
      - miked10_sound
      - miked11_sound
      - mikedmike1_sound
      - mikedmike2_sound
      - mikedrobot_sound


sound_player:
  miked1_sound:
    name_miked_1:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked2_sound:
    name_miked_2:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked3_sound:
    name_miked_3:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked4_sound:
    name_miked_4:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked5_sound:
    name_miked_5:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked6_sound:
    name_miked_6:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked7_sound:
    name_miked_7:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked8_sound:
    name_miked_8:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked9_sound:
    name_miked_9:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked10_sound:
    name_miked_10:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  miked11_sound:
    name_miked_11:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  mikedrobot_sound:
    name_miked_robot:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  mikedmike1_sound:
    name_miked_michaeldiamond:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice
  mikedmike2_sound:
    name_miked_michaeldiamond2:
      action: load
      bus: voice
    superspins_callout:
      action: load
      bus: voice

